import test from 'node:test';
import assert from 'node:assert/strict';
import {mapArchitecture,parseAndrevichReleases,parseRemittorManifest,detectProvider,compareApkVersions} from './lib/engine-provider-logic.mjs';
const arch='aarch64_cortex-a53',sha='a'.repeat(64);
function a(name,overrides={}){return Object.assign({name,state:'uploaded',size:564500,digest:`sha256:${sha}`,browser_download_url:`https://github.com/1andrevich/zapret2-openwrt/releases/download/v1.0.3/${name}`},overrides);}
test('architecture mapping prefers exact APK architecture',()=>{assert.equal(mapArchitecture({distribArch:'aarch64_generic',apkArch:arch}),arch);assert.equal(mapArchitecture({distribArch:'x86_64',apkArch:'x86_64'}),'x86_64');assert.equal(mapArchitecture({distribArch:'unknown',apkArch:'unknown'}),null);});
test('1andrevich selects only published stable engine APK',()=>{const doc=[{id:358634632,tag_name:'v1.0.3',draft:false,prerelease:false,published_at:'2026-07-23T11:22:44Z',assets:[a('luci-app-zapret2.apk'),a(`zapret2_${arch}.ipk`),a(`zapret2_${arch}.apk`)]}];const c=parseAndrevichReleases(doc,arch);assert.equal(c.assetName,`zapret2_${arch}.apk`);assert.equal(c.packageVersion,'1.0.3');assert.equal(c.sha256,sha);});
test('1andrevich ignores prerelease and branch-only versions',()=>{const doc=[{id:2,tag_name:'v1.0.4',draft:false,prerelease:true,published_at:'x',assets:[a(`zapret2_${arch}.apk`)]},{id:1,tag_name:'v1.0.3',draft:false,prerelease:false,published_at:'x',assets:[a(`zapret2_${arch}.apk`)]}];assert.equal(parseAndrevichReleases(doc,arch).version,'1.0.3');});
test('provider parsers reject missing asset, digest and malformed metadata',()=>{assert.throws(()=>parseAndrevichReleases(null,arch),/metadata/);assert.throws(()=>parseAndrevichReleases([{id:1,tag_name:'v1.0.3',draft:false,prerelease:false,published_at:'x',assets:[]}],arch),/asset/);assert.throws(()=>parseAndrevichReleases([{id:1,tag_name:'v1.0.3',draft:false,prerelease:false,published_at:'x',assets:[a(`zapret2_${arch}.apk`,{digest:null})]}],arch),/digest/);});
test('Remittor selects architecture ZIP for engine-only extraction',()=>{const name=`zapret2_v0.9.20260307_${arch}.zip`,doc={generated_at:'2026-03-07T07:32:52Z',releases:[{tag:'v0.9.20260307',prerelease:false,published_at:'2026-03-07T06:27:30Z',assets:[{id:368761307,name,state:'uploaded',size:847585,digest:`sha256:${sha}`,browser_download_url:`https://github.com/remittor/zapret-openwrt/releases/download/v0.9.20260307/${name}`}]}]};const c=parseRemittorManifest(doc,arch);assert.equal(c.packageVersion,'0.9.20260307');assert.equal(c.container,'zip');assert.equal(c.packageAssetPattern,'zapret2-*.apk');});
test('APK comparison is release aware',()=>{assert.equal(compareApkVersions('1.0.3-r1','1.0.3-r2'),-1);assert.equal(compareApkVersions('1.0.3','1.0.3-r1'),-1);assert.equal(compareApkVersions('1.0.4-r1','1.0.3-r9'),1);});
test('provenance is evidence-based and otherwise unknown',()=>{assert.equal(detectProvider({name:'zapret2',version:'0.9.20260307-r3',providerMarker:'remittor/zapret-openwrt'},null),'remittor');assert.equal(detectProvider({name:'zapret2',version:'1.0.3',runtimeVersion:'b78b52c'},null),'andrevich');assert.equal(detectProvider({name:'zapret2',version:'9.9.9',runtimeContract:true},{provider:'remittor',packageVersion:'0.9.20260307'}),'unknown');});
