import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root = path.resolve(import.meta.dirname, '..', '..');
const modelPath = path.join(root, 'luci-app-zapret2-manager/files/www/luci-static/resources/view/zapret2-manager/z2m-strategies-model.js');
const pagePath = path.join(root, 'luci-app-zapret2-manager/files/www/luci-static/resources/view/zapret2-manager/z2m-strategies.js');
const donorPath = path.join('G:', 'avatarDD', 'zapret-gui-p03', 'web', 'js', 'pages', 'strategies.js');
const corpusPath = path.join(root, 'zapret2-manager/files/usr/libexec/zapret2-manager/catalog/stressozz-corpus.json');

function loadModel() {
  const source = fs.readFileSync(modelPath, 'utf8');
  return vm.runInNewContext(`(function () { ${source}\n })()`, {
    baseclass: { extend: (value) => value }
  });
}

test('collapsed Strategy metadata preserves donor protocol and real port/range tags', () => {
  const model = loadModel();
  const tags = model.strategyProfileTags({ protocol: 'tcp', profiles: [
    { id: 'tcp1', name: 'Профиль 1', args: '--filter-tcp=2053,2083,2087,2096,8443 --lua-desync=fake' },
    { id: 'udp1', name: 'Профиль 2', args: '--filter-udp=19294-19344,50000-50100 --lua-desync=fake' }
  ] });
  assert.deepEqual(JSON.parse(JSON.stringify(tags.map((tag) => tag.label))), [
    'TCP (порты 2053,2083,2087,2096,8443)',
    'UDP (порты 19294-19344,50000-50100)'
  ]);
});

test('port metadata accepts canonical profile filter fields without flattening ranges', () => {
  const model = loadModel();
  const tags = model.strategyProfileTags({ protocol: 'udp', profiles: [
    { id: 'p1', name: 'Профиль 1', filters: { udpPorts: '88,1024-2407,2409-4499' }, args: '--lua-desync=fake' },
    { id: 'p2', name: 'Профиль 2', tcpPorts: '2802,2302,2502,3724,6000-8000', args: '--lua-desync=fake' }
  ] });
  assert.deepEqual(JSON.parse(JSON.stringify(tags.map((tag) => tag.label))), [
    'UDP (порты 88,1024-2407,2409-4499)',
    'TCP (порты 2802,2302,2502,3724,6000-8000)'
  ]);
});

test('identical protocol and port tags are emitted once across profiles', () => {
  const model = loadModel();
  const tags = model.strategyProfileTags({ protocol: 'udp', profiles: [
    { id: 'udp1', name: 'Профиль 1', udpPorts: '443', args: '--filter-udp=443 --lua-desync=fake' },
    { id: 'udp2', name: 'Профиль 2', udpPorts: '443', args: '--filter-udp=443 --lua-desync=multisplit' }
  ] });
  assert.deepEqual(JSON.parse(JSON.stringify(tags.map((tag) => tag.label))), [
    'UDP (порты 443)'
  ]);
});

test('noisy canonical port fields do not leak following arguments into a badge', () => {
  const model = loadModel();
  const tags = model.strategyProfileTags({ protocol: 'tcp', profiles: [
    { id: 'tcp1', name: 'Профиль 1', tcpPorts: '80,443 --filter-l7=tls,http --out-range=-s34228', args: '--lua-desync=fake' }
  ] });
  assert.deepEqual(JSON.parse(JSON.stringify(tags.map((tag) => tag.label))), [
    'TCP (порты 80,443)'
  ]);
});

test('autogenerated profile names never replace missing port semantics', () => {
  const model = loadModel();
  const tags = model.strategyProfileTags({ protocol: 'tcp', profiles: [
    { id: 'profile1', name: 'Profile 1', args: '--lua-desync=multisplit:pos=host' }
  ] });
  assert.deepEqual(JSON.parse(JSON.stringify(tags.map((tag) => tag.label))), ['TCP']);
});

test('donor renderer and canonical corpus provide the source semantics', () => {
  const donor = fs.readFileSync(donorPath, 'utf8');
  const corpus = JSON.parse(fs.readFileSync(corpusPath, 'utf8'));
  const page = fs.readFileSync(pagePath, 'utf8');
  assert.match(donor, /function _detectProfileInfo[\s\S]*--filter-tcp=[\s\S]*TCP \(порты /);
  assert.match(donor, /function _detectProfileInfo[\s\S]*--filter-udp=[\s\S]*UDP \(порты /);
  assert.ok(corpus.records.some((record) => record.filters && record.filters.tcpPorts === '2053,2083,2087,2096,8443'));
  assert.ok(corpus.records.some((record) => record.filters && record.filters.udpPorts === '19294-19344,50000-50100'));
  assert.doesNotMatch(page, /TCP \(порты (?:80|443|2053|19294)/);
  assert.match(page, /Model\.strategyProfileTags/);
});
