'use strict';

/* Background Block Detector contract.  It is intentionally not the one-shot
 * BlockCheck model: discovery and repeated observation are its product. */
const SOURCES = { auto: true, dnsmasq_log: true, adguard_log: true, af_packet: true };
function object(value) { return type(value) == 'object' && value != null; }
function fail(message, path) { let out = { ok: false, error: { code: 'EINPUT', message: message } }; if (path != null) out.error.path = path; return out; }
function lower(value) { let out = ''; for (let i = 0; i < length(value); i++) { let c = ord(substr(value, i, 1)); out += c >= 65 && c <= 90 ? chr(c + 32) : substr(value, i, 1); } return out; }
function host(value) { if (type(value) != 'string') return null; let d = trim(value); if (substr(d, -1) == '.') d = substr(d, 0, -1); if (length(d) < 2 || length(d) > 253 || !match(d, /^[A-Za-z0-9.-]+$/) || index(d, '..') >= 0) return null; let labels = split(d, '.'); if (length(labels) < 2) return null; for (let label in labels) if (!length(label) || substr(label, 0, 1) == '-' || substr(label, -1) == '-') return null; return lower(d); }
export const block_detector_request_validate = function(input) { if (!object(input)) return fail('Block Detector request must be an object', 'request'); for (let key in input) if (key != 'enabled' && key != 'intervalSec' && key != 'dnsSource' && key != 'whitelist' && key != 'probeTimeout') return fail('unknown Block Detector field', key); let interval = input.intervalSec == null ? 300 : input.intervalSec, timeout = input.probeTimeout == null ? 5 : input.probeTimeout, source = input.dnsSource == null ? 'auto' : input.dnsSource; if (type(interval) != 'int' || interval < 10 || interval > 86400) return fail('intervalSec is out of bounds', 'intervalSec'); if (type(timeout) != 'int' || timeout < 1 || timeout > 60) return fail('probeTimeout is out of bounds', 'probeTimeout'); if (!SOURCES[source]) return fail('dnsSource is unsupported', 'dnsSource'); let whitelist = [], seen = {}; if (input.whitelist != null && type(input.whitelist) != 'array') return fail('whitelist must be an array', 'whitelist'); for (let raw in input.whitelist || []) { let d = host(raw); if (d == null) return fail('whitelist contains an invalid domain', 'whitelist'); if (!seen[d]) { seen[d] = true; push(whitelist, d); } } if (length(whitelist) > 256) return fail('whitelist is too large', 'whitelist'); return { ok: true, value: { enabled: input.enabled == true, intervalSec: interval, dnsSource: source, whitelist: whitelist, probeTimeout: timeout } }; };
export const block_detector_classify_observation = function(value) { if (!object(value) || !object(value.dns) || !object(value.tcp) || !object(value.tls) || !object(value.http)) return { outcome: 'infrastructure', infrastructure: { code: 'malformed_observation' }, finding: null }; if (value.dns.status == 'unavailable' || value.tcp.status == 'unavailable' || value.tls.status == 'unavailable') return { outcome: 'infrastructure', infrastructure: { code: 'dependency_unavailable', evidence: value }, finding: null }; let domain = value.domain, kind = 'none', protocol = 'https', recommendation = 'none'; if (value.dns.fake == true || value.dns.status == 'failed') { kind = 'dns_block'; protocol = 'dns'; recommendation = 'dns'; } else if (value.tcp.status == 'failed' || value.tcp.status == 'timeout') { kind = 'tcp_refused'; protocol = 'tcp'; recommendation = 'routing/tunnel'; } else if (value.tls.reset == true || value.tls.status == 'reset') { kind = 'tls_rst'; protocol = 'tls'; recommendation = 'scanner/zapret'; } else if (value.http.cutoff == true || value.http.status == 'cutoff') { kind = 'http_cutoff'; recommendation = 'scanner/zapret'; } return { outcome: 'finding', finding: { classification: kind, confidence: kind == 'none' ? 'medium' : 'high', protocol: protocol, domains: [domain], evidence: [value], recommendation: recommendation, source: 'block-detector' }, infrastructure: [] }; };
export const block_detector_result_validate = function(value) { if (!object(value) || value.schema !== 1 || type(value.results) != 'array' || type(value.discovered) != 'array') return fail('Block Detector result schema is invalid', 'result'); return { ok: true, value: value }; };
