'use strict';

import { readfile, writefile, stat, lsdir, readlink, popen } from 'fs';
import * as model from './block-detector-model.uc';

const ROOT = '/tmp/zapret2-manager/jobs';
const RUNNER = '/usr/libexec/zapret2-manager/block-detector-run.sh';
function path(suffix) { return ROOT + '/block-detector' + suffix; }
function object(value) { return type(value) == 'object' && value != null; }
function quote(value) { let out = "'", text = '' + value; for (let i = 0; i < length(text); i++) out += substr(text, i, 1) == "'" ? "'\\''" : substr(text, i, 1); return out + "'"; }
function run(cmd) { let p = popen(cmd + ' 2>/dev/null', 'r'); if (!p) return ''; let out = p.read('all') || ''; p.close(); return out; }
function save(value) { writefile(path('.json'), sprintf('%J', value) + '\n'); }
function load() { let raw = readfile(path('.json')); if (!raw) return null; try { let value = json(raw); return object(value) ? value : null; } catch (e) { return null; } }
function identity(pid) { if (type(pid) != 'int' || pid <= 0 || !stat('/proc/' + pid)) return null; let raw = readfile('/proc/' + pid + '/stat'), close = raw ? index(raw, ')') : -1; if (close < 0) return null; let fields = split(trim(substr(raw, close + 1)), ' '), start = length(fields) > 19 ? +fields[19] : 0; return start ? { pid: pid, startTime: start, exe: readlink('/proc/' + pid + '/exe') || '', cmdline: readfile('/proc/' + pid + '/cmdline') || '' } : null; }
function owned(job) { let actual = object(job && job.runner) ? identity(job.runner.pid) : null; return actual && actual.startTime == job.runner.startTime && actual.exe == job.runner.exe && index(actual.cmdline, 'block-detector-run.sh') >= 0 ? actual : null; }
function public_job(job) { return job ? { id: job.id, product: 'block-detector', status: job.status, phase: job.phase, running: job.status == 'running', source: job.config.dnsSource, intervalSec: job.config.intervalSec, discoveredCount: length(job.discovered || []), resultCount: length(job.results || []), startedAt: job.startedAt, finishedAt: job.finishedAt, recovery: job.recovery, error: job.error } : null; }
function error(code, message) { return { ok: false, error: { code: code, message: message } }; }
function discover(config) { let source = config.dnsSource; if (source == 'auto') source = stat('/var/log/dnsmasq.log') ? 'dnsmasq_log' : (stat('/opt/etc/AdGuardHome/data/querylog.json') ? 'adguard_log' : 'af_packet'); let raw = source == 'dnsmasq_log' ? readfile('/var/log/dnsmasq.log') : source == 'adguard_log' ? readfile('/opt/etc/AdGuardHome/data/querylog.json') : ''; if (!raw) return { source: source, domains: [], dependency: source == 'af_packet' ? 'af_packet_unavailable' : 'log_unavailable' }; let out = [], seen = {}; let lines = split(substr(raw, length(raw) > 65536 ? length(raw) - 65536 : 0), '\n'); for (let line in lines) { let candidate = null; if (source == 'dnsmasq_log') { let words = split(trim(line), ' '); for (let i = 0; i + 1 < length(words); i++) if (words[i] == 'reply') candidate = words[i + 1]; } else { try { let item = json(line); if (object(item)) candidate = item.domain; } catch (e) { } } if (candidate == null) continue; let d = null; try { d = model.block_detector_request_validate({ whitelist: [candidate] }).value.whitelist[0]; } catch (e) { d = null; } if (d != null && !seen[d]) { seen[d] = true; push(out, d); } } return { source: source, domains: out }; }
function probe(domain, timeout) { if (!length(run('command -v nslookup')) || !length(run('command -v nc')) || !length(run('command -v curl'))) return { domain: domain, dns: { status: 'unavailable' }, tcp: { status: 'unavailable' }, tls: { status: 'unavailable' }, http: { status: 'unavailable' } }; let dns = run('nslookup ' + quote(domain)), tcp = run('nc -z -w ' + timeout + ' ' + quote(domain) + ' 443; echo $?'), body = '/tmp/z2m-detector-' + time() + '.body', code = trim(run('curl -4 -k -sS --connect-timeout ' + timeout + ' --max-time ' + timeout + ' -o ' + quote(body) + ' -w %{http_code} https://' + quote(domain) + '/')); let bytes = +(trim(run('wc -c < ' + quote(body))) || 0); run('rm -f ' + quote(body)); return { domain: domain, dns: { status: length(dns) ? 'success' : 'failed' }, tcp: { status: trim(tcp) == '0' ? 'success' : 'failed' }, tls: { status: code != '000' && length(code) ? 'success' : 'reset' }, http: { status: code == '000' ? 'cutoff' : 'success', code: code, bytes: bytes } }; }
export const block_detector_start = function(input) { let current = load(); if (current && current.status == 'running') { if (owned(current)) return { ok: true, job: public_job(current) }; current.status = 'error'; current.phase = 'recovery'; current.recovery = { state: 'uncertain' }; current.error = { code: 'ESTALE', message: 'Block Detector worker disappeared; recovery is fail-closed' }; current.finishedAt = time(); save(current); } let checked = model.block_detector_request_validate(input || { enabled: true }); if (!checked.ok) return checked; if (!stat(RUNNER)) return error('EDEPENDENCY', 'Block Detector runner is unavailable'); let job = { schema: 1, id: 'block-detector', product: 'block-detector', status: 'running', phase: 'monitoring', config: checked.value, discovered: [], results: [], managedListCandidates: [], runner: null, startedAt: time(), finishedAt: null, recovery: { state: 'not_required' }, error: null }; save(job); writefile(path('.env'), 'INTERVAL=' + checked.value.intervalSec + '\n'); let pid = +trim(run('setsid ash ' + quote(RUNNER) + ' </dev/null >/dev/null 2>&1 & echo $!')), value = identity(pid); if (!value) { job.status = 'error'; job.error = { code: 'EOWNERSHIP', message: 'Block Detector runner identity is not verifiable' }; save(job); return error('EOWNERSHIP', 'Block Detector runner identity is not verifiable'); } value.fingerprint = 'block-detector-run.sh'; job.runner = value; save(job); return { ok: true, job: public_job(job) }; };
export const block_detector_status = function() { let job = load(); if (job && job.status == 'running' && !owned(job)) { job.status = 'error'; job.phase = 'recovery'; job.recovery = { state: 'uncertain' }; job.error = { code: 'ESTALE', message: 'Block Detector worker disappeared' }; job.finishedAt = time(); save(job); } return { ok: true, job: public_job(job) }; };
export const block_detector_results = function() { let job = load(); return { ok: true, results: job ? { schema: 1, id: job.id, product: 'block-detector', status: job.status, discovered: job.discovered || [], results: job.results || [], managedListCandidates: job.managedListCandidates || [], source: job.config.dnsSource } : null }; };
export const block_detector_stop = function() { let job = load(); if (!job || job.status != 'running') return { ok: true, status: 'idle' }; if (!owned(job)) return error('EOWNERSHIP', 'Block Detector runner is not owned'); writefile(path('.cancel'), '' + time() + '\n'); job.status = 'cancelling'; job.phase = 'cancelling'; save(job); run('kill -TERM -' + job.runner.pid); return { ok: true, status: 'cancelling', id: job.id }; };
export const block_detector_tick = function() { let job = load(); if (!job || job.status != 'running') return error('ESTATE', 'Block Detector is not running'); let found = discover(job.config), whitelist = {}; for (let d in job.config.whitelist) whitelist[d] = true; let candidates = []; for (let d in found.domains) { if (whitelist[d]) continue; let exists = false; for (let old in job.discovered) if (old == d) exists = true; if (!exists) push(job.discovered, d); } let checks = []; for (let d in found.domains) if (!whitelist[d]) { let observation = probe(d, job.config.probeTimeout), classified = model.block_detector_classify_observation(observation); if (classified.finding) { push(checks, classified.finding); if (classified.finding.classification != 'none') push(job.managedListCandidates, d); } } job.results = checks; job.lastDiscovery = { source: found.source, dependency: found.dependency || null, at: time() }; save(job); return { ok: true, discovered: job.discovered, results: checks }; };
export const block_detector_mark_stopped = function() { let job = load(); if (job) { job.status = 'stopped'; job.phase = 'stopped'; job.finishedAt = time(); job.recovery = { state: 'verified' }; save(job); } return { ok: true }; };
let commandName = ARGV[0]; if (commandName != null) { let input = null; if (ARGV[1]) { let raw = readfile(ARGV[1]); try { input = raw ? json(raw) : null; } catch (e) { input = null; } } let answer = commandName == 'start' ? block_detector_start(input) : commandName == 'status' ? block_detector_status() : commandName == 'results' ? block_detector_results() : commandName == 'stop' ? block_detector_stop() : commandName == 'tick' ? block_detector_tick() : commandName == 'stopped' ? block_detector_mark_stopped() : error('EINPUT', 'unknown command'); print(sprintf('%J', answer) + '\n'); }
