'use strict';
import { readfile, writefile, stat, mkdir, unlink, popen } from 'fs';
import { metadata as and_metadata, resolveLatest as and_latest, verifyMetadata as and_verify, detectInstalled as and_detect } from './providers/andrevich.uc';
import { metadata as rem_metadata, resolveLatest as rem_latest, verifyMetadata as rem_verify, detectInstalled as rem_detect } from './providers/remittor.uc';
const CHECK_DIR='/tmp/zapret2-manager/engine-checks', STATE_FILE='/etc/zapret2-manager/engine-provider.json', CACHE_APK='/etc/zapret2-manager/engine-cache/current.apk', CHECK_TTL=600, MAX_METADATA=4194304;
const ARCHES=['aarch64_cortex-a53','aarch64_cortex-a72','aarch64_cortex-a76','aarch64_generic','arm_arm1176jzf-s_vfp','arm_arm926ej-s','arm_cortex-a15_neon-vfpv4','arm_cortex-a5','arm_cortex-a5_vfpv4','arm_cortex-a7','arm_cortex-a7_neon-vfpv4','arm_cortex-a7_vfpv4','arm_cortex-a8','arm_cortex-a8_vfpv3','arm_cortex-a9','arm_cortex-a9_neon','arm_cortex-a9_vfpv3-d16','arm_fa526','arm_mpcore','arm_xscale','i386_pentium-mmx','i386_pentium4','mips64_octeonplus','mips_24kc','mips_4kec','mips_mips32','mipsel_24kc','mipsel_24kc_24kf','mipsel_74kc','mipsel_mips32','powerpc_464fp','powerpc_8540','riscv64_riscv64','riscv64_generic','x86_64','x86_geode'];
function run(command){let p=popen(command+' 2>/dev/null','r');if(!p)return{rc:-1,out:''};let out=p.read('all'),rc=p.close();return{rc:rc,out:out?out:''};}
function fail(code,message,details){let r={ok:false,error:{code:code,message:message}};if(details!=null)r.error.details=details;return r;}
function literal(v){return type(v)=='string'&&index(v,"'")<0&&index(v,'\n')<0&&index(v,'\r')<0?"'"+v+"'":null;}
function safe_arch(v){for(let i=0;i<length(ARCHES);i++)if(ARCHES[i]==v)return v;return null;}
function safe_token(v){return type(v)=='string'&&match(v,/^[a-f0-9]{48}$/)?v:null;}
function safe_version(v){return type(v)=='string'&&match(v,/^[A-Za-z0-9][A-Za-z0-9._+~-]{0,95}$/)?v:null;}
function read_json(path,fallback){try{let raw=readfile(path);return raw?json(raw):fallback;}catch(e){return fallback;}}
function ensure_dir(path){try{mkdir(path);}catch(e){}let q=literal(path);if(q!=null)run('chmod 700 '+q);}
function atomic_json(path,value){let tmp=path+'.tmp.'+time()+'-'+length(sprintf('%J',value));if(!writefile(tmp,sprintf('%J',value)+'\n'))return false;let a=literal(tmp),b=literal(path);if(a==null||b==null)return false;let r=run('chmod 600 '+a+' && mv -f '+a+' '+b);if(r.rc!=0){try{unlink(tmp);}catch(e){}return false;}return stat(path)!=null;}
function adapter(id){if(id=='andrevich')return{id:id,label:'1andrevich',metadata:and_metadata,latest:and_latest,verify:and_verify,detect:and_detect};if(id=='remittor')return{id:id,label:'Remittor',metadata:rem_metadata,latest:rem_latest,verify:rem_verify,detect:rem_detect};return null;}
function architecture(){let a=trim(run('apk --print-arch').out);if(safe_arch(a)!=null)return a;a=trim(run(". /etc/openwrt_release 2>/dev/null; printf '%s' \"$DISTRIB_ARCH\"").out);return safe_arch(a);}
function metadata_allowed(d){if(type(d)!='object'||d==null||type(d.url)!='string')return false;if(d.provider=='andrevich')return d.url=='https://api.github.com/repos/1andrevich/zapret2-openwrt/releases?per_page=20';let prefix='https://raw.githubusercontent.com/remittor/zapret-openwrt/gh-pages/releases/releases_zap2_',suffix='.json';if(d.provider!='remittor'||substr(d.url,0,length(prefix))!=prefix||substr(d.url,length(d.url)-length(suffix))!=suffix)return false;return safe_arch(substr(d.url,length(prefix),length(d.url)-length(prefix)-length(suffix)))!=null;}
function fetch_json(d){if(!metadata_allowed(d))return fail('ESECURITY','Metadata URL не входит в allowlist.');ensure_dir('/tmp/zapret2-manager');let file='/tmp/zapret2-manager/engine-metadata.'+time()+'.'+d.provider,qf=literal(file),qu=literal(d.url);if(qf==null||qu==null)return fail('ESECURITY','Metadata URL не прошёл shell boundary.');let r=run('ulimit -f 8192; uclient-fetch -q -T 20 --user-agent zapret2-manager/engine -O '+qf+' '+qu),s=stat(file);if(r.rc!=0||s==null){try{unlink(file);}catch(e){}return fail('ENETWORK','Не удалось получить metadata поставщика.');}if(s.size<2||s.size>MAX_METADATA){try{unlink(file);}catch(e){}return fail('EMETADATA','Metadata имеет недопустимый размер.');}let doc=read_json(file,null);try{unlink(file);}catch(e){}return doc!=null?{ok:true,document:doc}:fail('EMETADATA','Metadata поставщика повреждена.');}
function random_token(){return trim(run("od -An -N24 -tx1 /dev/urandom | tr -d ' \\n'").out);}
function public_candidate(c){return{provider:c.provider,version:c.version,packageVersion:c.packageVersion,upstreamVersion:c.upstreamVersion,upstreamCommit:c.upstreamCommit,architecture:c.architecture,assetName:c.assetName,sha256:c.sha256,size:c.size,releaseId:c.releaseId,publishedAt:c.publishedAt,prerelease:c.prerelease,compatible:c.compatible,compatibilityMessage:c.compatibilityMessage};}
function package_version(){let s=trim(run('apk info -v zapret2 | head -n 1').out);return substr(s,0,8)=='zapret2-'?substr(s,8):s;}
function description(raw){let lines=split(raw,'\n');for(let i=0;i<length(lines);i++){let l=lc(trim(lines[i]));if((l=='description:'||l=='description')&&i+1<length(lines))return trim(lines[i+1]);if(substr(l,0,12)=='description:')return trim(substr(lines[i],12));}return '';}
function runtime_version(){return stat('/opt/zapret2/nfq2/nfqws2')!=null?trim(run('/opt/zapret2/nfq2/nfqws2 --version | head -n 1').out):'';}
function marker(){let paths=['/opt/zapret2/update-pkg.sh','/opt/zapret2/update.sh'];for(let i=0;i<length(paths);i++)try{let s=readfile(paths[i]);if(s&&length(s)<=131072&&index(s,'remittor/zapret-openwrt')>=0)return'remittor/zapret-openwrt';}catch(e){}return '';}
function file_sha(path){let q=literal(path);if(q==null||stat(path)==null)return null;let h=trim(run("sha256sum "+q+" | awk '{print $1}'").out);return match(h,/^[a-f0-9]{64}$/)?h:null;}
function saved_state(){return read_json(STATE_FILE,null);}
function package_meta(saved){if(run('apk info -e zapret2').rc!=0)return null;let raw=run('apk info -a zapret2').out,digest=file_sha(CACHE_APK);return{name:'zapret2',version:package_version(),description:description(raw),runtimeVersion:runtime_version(),providerMarker:marker(),managedAssetSha256:type(saved)=='object'&&saved!=null&&digest==saved.assetSha256?digest:null,runtimeContract:stat('/opt/zapret2/config')!=null&&stat('/opt/zapret2/nfq2/nfqws2')!=null&&stat('/etc/init.d/zapret2')!=null};}
function package_files(){let lines=split(run('apk info -L zapret2').out,'\n'),out=[];for(let i=0;i<length(lines);i++){let l=trim(lines[i]);if(substr(l,0,1)=='/')push(out,l);}return out;}
function compare_versions(a,b){if(safe_version(a)==null||safe_version(b)==null)return null;let r=trim(run('apk version -t '+literal(a)+' '+literal(b)).out);return r=='<'?-1:(r=='>'?1:(r=='='?0:null));}
export const engine_providers=function(){let a=architecture();return{ok:true,packageManager:'apk',architecture:a,providers:[{id:'remittor',label:'Remittor',channel:'stable',supported:a!=null},{id:'andrevich',label:'1andrevich',channel:'stable',supported:a!=null}],latestOnly:true};};
export const installed_engine=function(){let saved=saved_state(),meta=package_meta(saved);if(meta==null)return{installed:false,packageName:null,packageVersion:null,provider:null,providerConfidence:null,savedState:saved,architecture:architecture(),runtimeVersion:null,runtimeContract:false};let files=package_files(),all=[rem_detect(meta,files,saved),and_detect(meta,files,saved)],winner=null;for(let i=0;i<length(all);i++){let x=all[i];if(x.provider=='unknown')continue;if(winner!=null&&winner.provider!=x.provider){winner=null;break;}winner=x;}return{installed:true,packageName:'zapret2',packageVersion:meta.version,packageDescription:meta.description,provider:winner!=null?winner.provider:'unknown',providerConfidence:winner!=null?winner.confidence:'none',providerEvidence:winner!=null?winner.evidence:null,savedState:saved,architecture:architecture(),files:files,runtimeVersion:meta.runtimeVersion,runtimeContract:meta.runtimeContract};};
export const engine_check_updates=function(input){if(type(input)!='object'||input==null||type(input.provider)!='string')return fail('EINPUT','Нужно выбрать поставщика.');let p=adapter(input.provider),channel=input.channel!=null?input.channel:'stable',arch=architecture();if(p==null||channel!='stable')return fail('EINPUT','Неизвестный поставщик или channel.');if(arch==null)return fail('EARCH','Архитектура устройства не поддерживается.');let fetched=fetch_json(p.metadata(arch));if(!fetched.ok)return fetched;let c=p.latest(arch,channel,fetched.document);if(c==null)return fail('ENOASSET','Опубликованный engine asset для этой архитектуры не найден.');if(!p.verify(c))return fail('EMETADATA','Metadata кандидата не прошла проверку.');let token=random_token();if(safe_token(token)==null)return fail('EINTERNAL','Не удалось создать check token.');ensure_dir('/tmp/zapret2-manager');ensure_dir(CHECK_DIR);let now=time(),record={schema:'engine-check.v1',token:token,provider:p.id,channel:channel,checkedAt:now,expiresAt:now+CHECK_TTL,candidate:c};if(!atomic_json(CHECK_DIR+'/'+token+'.json',record))return fail('EINTERNAL','Не удалось сохранить проверенный кандидат.');let installed=installed_engine(),same=installed.installed&&installed.provider==p.id,cmp=installed.installed&&c.packageVersion!=null?compare_versions(installed.packageVersion,c.packageVersion):null;return{ok:true,checkToken:token,checkedAt:now,expiresAt:now+CHECK_TTL,installedVersion:installed.packageVersion,providerLatestVersion:c.packageVersion!=null?c.packageVersion:c.version,upstreamLatestVersion:c.upstreamVersion,updateAvailable:same&&cmp!=null&&cmp<0,sameProvider:same,providerSwitch:installed.installed&&!same,compatible:c.compatible===true,compatibilityMessage:c.compatibilityMessage,candidate:public_candidate(c)};};
export const load_checked_candidate=function(providerId,token){if(adapter(providerId)==null||safe_token(token)==null)return fail('EINPUT','Некорректный provider или check token.');let path=CHECK_DIR+'/'+token+'.json',record=read_json(path,null);if(record==null||record.provider!=providerId||record.token!=token)return fail('ECHECKTOKEN','Проверенный кандидат не найден.');if(+record.expiresAt<time()){try{unlink(path);}catch(e){}return fail('ECHECKEXPIRED','Результат проверки устарел.');}let p=adapter(providerId);if(!p.verify(record.candidate))return fail('EMETADATA','Кандидат не прошёл повторную проверку.');if(record.candidate.compatible!==true||record.candidate.packageVersion==null)return fail('EINCOMPATIBLE','Совместимость версии не подтверждена.');try{unlink(path);}catch(e){}return{ok:true,record:record};};
export const save_engine_provider_state=function(v){ensure_dir('/etc/zapret2-manager');return atomic_json(STATE_FILE,v);};
export const clear_engine_provider_state=function(){try{unlink(STATE_FILE);}catch(e){}return stat(STATE_FILE)==null;};
