'use strict';
import { readfile,writefile,stat,mkdir,unlink,popen } from 'fs';
import { engine_providers as provider_list,installed_engine,engine_check_updates as provider_check,load_checked_candidate,save_engine_provider_state,clear_engine_provider_state } from './engine-providers.uc';
const ROOT='/tmp/zapret2-manager/engine-operations',ACTIVE=ROOT+'/active',WORKER='/usr/libexec/zapret2-manager/engine-operation-worker.sh';
const TERMINAL=['completed','failed','rolled_back'],PHASES=['queued','preflight','backup','stopping','downloading','verifying','installing','restoring','starting','postflight','completed','failed','rolling_back','rolled_back'];
function run(c){let p=popen(c+' 2>/dev/null','r');if(!p)return{rc:-1,out:''};let o=p.read('all'),r=p.close();return{rc:r,out:o?o:''};}
function fail(c,m,d){let r={ok:false,error:{code:c,message:m}};if(d!=null)r.error.details=d;return r;}
function safe_id(v){return type(v)=='string'&&match(v,/^eng-[0-9]+-[a-f0-9]{12}$/)?v:null;}
function allowed(v,list){for(let i=0;i<length(list);i++)if(list[i]==v)return true;return false;}
function terminal(v){return allowed(v,TERMINAL);}
function read_json(p,f){try{let r=readfile(p);return r?json(r):f;}catch(e){return f;}}
function atomic(p,v){let t=p+'.tmp.'+time();if(!writefile(t,sprintf('%J',v)+'\n'))return false;let r=run("chmod 600 '"+t+"' && mv -f '"+t+"' '"+p+"'");if(r.rc!=0){try{unlink(t);}catch(e){}return false;}return true;}
function setup(){try{mkdir('/tmp/zapret2-manager');}catch(e){}try{mkdir(ROOT);}catch(e){}run("chmod 700 '/tmp/zapret2-manager' '"+ROOT+"'");}
function new_id(){let e=trim(run("od -An -N6 -tx1 /dev/urandom | tr -d ' \\n'").out);return match(e,/^[a-f0-9]{12}$/)?'eng-'+time()+'-'+e:null;}
function path(id){return ROOT+'/'+id+'.json';}
function read_job(id){return safe_id(id)!=null?read_json(path(id),null):null;}
function active_id(){try{return trim(readfile(ACTIVE)||'');}catch(e){return'';}}
function log(job,msg){if(type(job.log)!='array')job.log=[];push(job.log,{at:time(),phase:job.phase,message:''+msg});while(length(job.log)>120)shift(job.log);}
function public_job(j){return j==null?null:{id:j.id,action:j.action,provider:j.provider,phase:j.phase,progress:j.progress,createdAt:j.createdAt,updatedAt:j.updatedAt,startedAt:j.startedAt,finishedAt:j.finishedAt,cancellable:j.cancellable===true,cancelRequested:j.cancelRequested===true,result:j.result,error:j.error,rollback:j.rollback,log:j.log||[]};}
function active_job(){let id=active_id();if(safe_id(id)==null)return null;let j=read_job(id);if(j==null||terminal(j.phase)){try{unlink(ACTIVE);}catch(e){}return null;}return j;}
function conflict(){if(active_job()!=null)return'engine-operation';if(stat('/tmp/zapret2-manager/pending-rollback')!=null||stat('/tmp/zapret2-manager/apply.lock')!=null)return'strategy';if(stat('/tmp/zapret2-manager/orchestra-apply.lock')!=null||stat('/tmp/zapret2-manager/orchestra-run.lock')!=null)return'orchestra';if(stat('/tmp/zapret2-manager/backup-restore.lock')!=null)return'backup-restore';let b=trim(run("grep -l '\"status\":\"\\(pending\\|running\\)\"' /tmp/zapret2-manager/jobs/*.json 2>/dev/null | head -n 1").out);return length(b)?'runtime-job':null;}
function start(action,provider,candidate,preserve){setup();let busy=conflict();if(busy!=null)return fail('EBUSY','Конфликтующая операция уже выполняется.',{conflict:busy});let id=new_id();if(id==null)return fail('EINTERNAL','Не удалось создать operation id.');let old=installed_engine(),actual=action;if(action=='install')actual=!old.installed?'install':(old.provider==provider?'update':'switch');let j={schema:'engine-operation.v1',id:id,action:actual,provider:provider,phase:'queued',progress:0,createdAt:time(),updatedAt:time(),startedAt:null,finishedAt:null,cancellable:true,cancelRequested:false,preserveConfig:preserve!==false,candidate:candidate,previous:old,result:null,error:null,rollback:null,log:[{at:time(),phase:'queued',message:'Операция поставлена в очередь.'}]};if(!atomic(path(id),j)||!writefile(ACTIVE,id+'\n'))return fail('ESTATE','Не удалось сохранить engine job.');run("chmod 600 '"+ACTIVE+"' '"+path(id)+"'");if(run("setsid '"+WORKER+"' '"+id+"' >/dev/null 2>&1 &").rc!=0)return fail('EWORKER','Не удалось запустить worker.');return{ok:true,operation:public_job(j)};}
function commit_of(i){let s=i.savedState;return i.provider!='unknown'&&type(s)=='object'&&s!=null&&s.provider==i.provider&&s.packageVersion==i.packageVersion?s.upstreamCommit:null;}
function version_matches(a,b){if(a==b)return true;let p=b+'-r';if(substr(a,0,length(p))!=p)return false;let s=substr(a,length(p));return length(s)>0&&match(s,/^[0-9]+$/);}
export const engine_providers=function(){return provider_list();};
export const engine_check_updates=function(i){return provider_check(i);};
export const engine_status=function(){let i=installed_engine(),a=active_job(),running=i.installed&&length(trim(run('pidof nfqws2').out))>0,compatible=!i.installed||i.runtimeContract===true;return{ok:true,state:a!=null?'operation':(i.installed?'installed':'engine_missing'),installed:i.installed,provider:i.provider,providerConfidence:i.providerConfidence,providerEvidence:i.providerEvidence,packageName:i.packageName,packageVersion:i.packageVersion,packageDescription:i.packageDescription,nfqws2Version:i.runtimeVersion,upstreamVersion:i.runtimeVersion,upstreamCommit:commit_of(i),architecture:i.architecture,serviceState:i.installed?(running?'running':'stopped'):'engine_missing',compatible:compatible,compatibilityMessage:compatible?(i.installed?'Runtime-контракт движка доступен.':'Установите совместимый движок.'):'Установленный пакет не соответствует runtime-контракту manager.',operation:public_job(a)};};
export const engine_install=function(i){if(type(i)!='object'||i==null||type(i.provider)!='string'||type(i.checkToken)!='string')return fail('EINPUT','Передайте provider и checkToken.');let c=load_checked_candidate(i.provider,i.checkToken);return c.ok?start('install',i.provider,c.record.candidate,true):c;};
export const engine_remove=function(i){if(type(i)!='object'||i==null||i.confirm!='REMOVE')return fail('EINPUT','Удаление требует подтверждение REMOVE.');let old=installed_engine();return old.installed?start('remove',old.provider,null,i.preserveConfig!==false):{ok:true,changed:false,state:'engine_missing'};};
export const engine_operation_status=function(i){let j=i!=null&&i.id!=null?read_job(i.id):active_job();return{ok:true,operation:public_job(j)};};
export const engine_operation_cancel=function(i){if(type(i)!='object'||i==null||safe_id(i.id)==null)return fail('EINPUT','Некорректный operation id.');let j=read_job(i.id);if(j==null)return fail('ENOENT','Engine operation не найдена.');if(terminal(j.phase))return{ok:true,changed:false,operation:public_job(j)};if(!j.cancellable)return fail('ENOTCANCELLABLE','Операция уже меняет пакет.');j.cancelRequested=true;j.updatedAt=time();log(j,'Запрошена отмена операции.');writefile(ROOT+'/'+j.id+'.cancel','cancel\n');atomic(path(j.id),j);return{ok:true,cancelling:true,operation:public_job(j)};};
export const mark_phase=function(id,phase,progress,message){if(safe_id(id)==null||!allowed(phase,PHASES))return fail('EINPUT','Некорректная фаза.');let j=read_job(id);if(j==null)return fail('ENOENT','Engine job не найдена.');let n=+progress;if(n<0)n=0;if(n>100)n=100;j.phase=phase;j.progress=n;j.updatedAt=time();if(j.startedAt==null&&phase!='queued')j.startedAt=time();j.cancellable=phase=='queued'||phase=='preflight'||phase=='backup'||phase=='downloading'||phase=='verifying';if(message)log(j,message);if(terminal(phase)){j.finishedAt=time();j.cancellable=false;try{unlink(ACTIVE);}catch(e){}}return atomic(path(id),j)?{ok:true,operation:public_job(j)}:fail('ESTATE','Job не сохранена.');};
export const mark_failed=function(id,code,message,rollback){let j=read_job(id);if(j==null)return fail('ENOENT','Job не найдена.');j.phase=rollback!=null&&rollback.verified?'rolled_back':'failed';j.progress=100;j.updatedAt=time();j.finishedAt=time();j.cancellable=false;j.error={code:code||'EENGINE',message:message||'Engine operation failed.'};j.rollback=rollback||null;log(j,j.error.message);let ok=atomic(path(id),j);try{unlink(ACTIVE);}catch(e){}return ok?{ok:true}:fail('ESTATE','Ошибка не сохранена.');};
export const mark_completed=function(id,result){let j=read_job(id);if(j==null)return fail('ENOENT','Job не найдена.');j.phase='completed';j.progress=100;j.updatedAt=time();j.finishedAt=time();j.cancellable=false;j.result=result||{ok:true};log(j,'Операция успешно завершена.');let ok=atomic(path(id),j);try{unlink(ACTIVE);}catch(e){}return ok?{ok:true}:fail('ESTATE','Результат не сохранён.');};
export const commit_state=function(id){let j=read_job(id);if(j==null||type(j.candidate)!='object'||j.candidate==null)return fail('ENOENT','Candidate job не найден.');let i=installed_engine(),c=j.candidate;if(!i.installed||i.packageName!='zapret2'||!version_matches(i.packageVersion,c.packageVersion)||i.runtimeContract!==true)return fail('EVERIFY','Установленный package не подтверждён.');let v={schema:'engine-provider.v1',provider:c.provider,packageVersion:i.packageVersion,assetName:c.assetName,assetSha256:c.sha256,releaseId:c.releaseId,upstreamVersion:c.upstreamVersion,upstreamCommit:c.upstreamCommit,architecture:c.architecture,installedAt:time()};return save_engine_provider_state(v)?{ok:true,state:v}:fail('ESTATE','Provider state не записан.');};
export const clear_state=function(){return clear_engine_provider_state()?{ok:true}:fail('ESTATE','Provider state не очищен.');};
export const job_for_worker=function(id){let j=read_job(id);return j!=null?{ok:true,job:j}:fail('ENOENT','Engine job не найдена.');};
