#!/usr/bin/ucode
'use strict';
import { readfile,popen } from 'fs';
import { engine_providers,engine_status,engine_check_updates,engine_install,engine_remove,engine_operation_status,engine_operation_cancel,mark_phase,mark_failed,mark_completed,commit_state,clear_state,job_for_worker } from './engine-manager.uc';
const LOCK='/tmp/zapret2-manager/engine-operation.lock';
function parse(path){if(path==null)return{};try{let r=readfile(path);return r?json(r):{};}catch(e){return{};}}
function output(v){print(sprintf('%J',v)+'\n');return type(v)=='object'&&v!=null&&v.ok===true;}
function safe_file(v){return type(v)=='string'&&match(v,/^\/tmp\/z2m-engine-edit\.[0-9]+\.[0-9]+$/)?v:null;}
function locked(mode,file){if(file!=null&&safe_file(file)==null){output({ok:false,error:{code:'EINPUT',message:'Некорректный request file.'}});return true;}let self='/usr/libexec/zapret2-manager/engine-cli.uc',cmd="Z2M_ENGINE_LOCKED=1 flock -n '"+LOCK+"' /usr/bin/ucode '"+self+"' '"+mode+"'";if(file!=null)cmd+=" '"+file+"'";let p=popen(cmd+' 2>/dev/null','r');if(!p)return false;let text=p.read('all'),rc=p.close();if(text)print(text);if(rc!=0&&!text)output({ok:false,error:{code:'EBUSY',message:'Другая engine-операция уже выполняется.'}});return true;}
let mode=length(ARGV)?ARGV[0]:'';if((mode=='install'||mode=='remove'||mode=='cancel')&&getenv('Z2M_ENGINE_LOCKED')==null)if(locked(mode,length(ARGV)>1?ARGV[1]:null))exit(0);
let r=null;if(mode=='providers')r=engine_providers();else if(mode=='status')r=engine_status();else if(mode=='check')r=engine_check_updates(parse(ARGV[1]));else if(mode=='install')r=engine_install(parse(ARGV[1]));else if(mode=='remove')r=engine_remove(parse(ARGV[1]));else if(mode=='operation')r=engine_operation_status(parse(ARGV[1]));else if(mode=='cancel')r=engine_operation_cancel(parse(ARGV[1]));else if(mode=='job')r=job_for_worker(ARGV[1]);else if(mode=='phase')r=mark_phase(ARGV[1],ARGV[2],+ARGV[3],ARGV[4]);else if(mode=='failed')r=mark_failed(ARGV[1],ARGV[2],ARGV[3],{attempted:ARGV[4]=='1',verified:ARGV[5]=='1',message:ARGV[6]||null});else if(mode=='complete')r=mark_completed(ARGV[1],parse(ARGV[2]));else if(mode=='commit-state')r=commit_state(ARGV[1]);else if(mode=='clear-state')r=clear_state();else r={ok:false,error:{code:'EINPUT',message:'Неизвестная engine command.'}};exit(output(r)?0:1);
