#!/usr/bin/ucode
'use strict';
import { readfile,popen } from 'fs';
import { engine_releases_read,engine_status,engine_check_release,engine_install,engine_update,engine_downgrade,engine_reinstall,engine_uninstall,engine_operation_status,engine_operation_cancel,mark_phase,mark_failed,mark_completed,commit_state,clear_state,job_for_worker } from './engine-manager.uc';
function parse(path){if(path==null)return{};try{let r=readfile(path);return r?json(r):{};}catch(e){return{};}}
function output(v){print(sprintf('%J',v)+'\n');return type(v)=='object'&&v!=null&&v.ok===true;}
let bootstrap=popen('/usr/libexec/zapret2-manager/z2m-root-bootstrap runtime 2>/dev/null','r');if(!bootstrap||bootstrap.close()!=0)exit(1);
let mode=length(ARGV)?ARGV[0]:'';let requestFile=length(ARGV)>1?ARGV[1]:null;if((mode=='check'||mode=='install'||mode=='remove'||mode=='operation'||mode=='cancel')&&requestFile!=null&&!match(requestFile,/^\/tmp\/z2m-engine-edit\.[A-Za-z0-9]+$/)){output({ok:false,error:{code:'EINPUT',message:'Некорректный request file.'}});exit(1);}
let r=null;if(mode=='releases')r=engine_releases_read();else if(mode=='status')r=engine_status();else if(mode=='check')r=engine_check_release(parse(ARGV[1]));else if(mode=='install')r=engine_install(parse(ARGV[1]));else if(mode=='update')r=engine_update(parse(ARGV[1]));else if(mode=='downgrade')r=engine_downgrade(parse(ARGV[1]));else if(mode=='reinstall')r=engine_reinstall(parse(ARGV[1]));else if(mode=='uninstall')r=engine_uninstall(parse(ARGV[1]));else if(mode=='operation')r=engine_operation_status(parse(ARGV[1]));else if(mode=='cancel')r=engine_operation_cancel(parse(ARGV[1]));else if(mode=='job')r=job_for_worker(ARGV[1]);else if(mode=='phase')r=mark_phase(ARGV[1],ARGV[2],+ARGV[3],ARGV[4]);else if(mode=='failed')r=mark_failed(ARGV[1],ARGV[2],ARGV[3],{attempted:ARGV[4]=='1',verified:ARGV[5]=='1',message:ARGV[6]||null});else if(mode=='complete')r=mark_completed(ARGV[1],parse(ARGV[2]));else if(mode=='commit-state')r=commit_state(ARGV[1]);else if(mode=='clear-state')r=clear_state();else r={ok:false,error:{code:'EINPUT',message:'Неизвестная engine command.'}};exit(output(r)?0:1);
