'use strict';
// lists.uc — list management backend for zapret2-manager (ЦЕЛЬ ДВА).
//
// The list-path MODEL is the shipped declarative manifest lists-model.json
// (installed next to this module; the path lives in constants.uc PATHS). The
// manifest is ROUTER-DERIVED from the live nfqws2 argv and upstream script
// semantics (its provenance field documents the evidence) — no guessed
// paths. tests/lists-model.test.mjs parses THE SAME manifest bytes and
// enforces the hard rules: no two editable keys share a path, engine-owned
// and unproven/generated lists reject writes, a key mapped to the wrong
// semantic type (a domain key pointed at an ipset file) rejects writes, and
// repeated active paths for one flag surface as ambiguity rather than
// collapsing to the first.
//
// Failure mode: a missing or invalid manifest fails CLOSED — lists_get
// returns an error envelope and lists_set refuses every write. The backend
// never falls back to guessed paths.
//
// Editable lists (proven user-maintained, referenced by the active argv):
// domain include and domain exclude. Read-only entries: the IP-semantic
// user keys (generated by upstream get scripts or without an engine
// consumer — the per-key reason explains) and the engine-owned
// autohostlist. A domain in BOTH include and exclude is an ERROR reported
// BEFORE apply. List content I/O goes through apply.uc (read_list_file /
// write_list_file) — the single writer. This module never touches nft or
// ipset.
//
// Mirrors tests/lib/lists-model.mjs (model rules) and
// tests/lib/lists-logic.mjs (normalize_domain, find_conflicts,
// check_domain). ucode does not run locally; the node self-tests prove the
// algorithm; runtime confirmed on target via smoke.sh.

import { readfile, stat } from 'fs';
import { read_list_file, write_list_file } from './apply.uc';
import { PATHS } from './constants.uc';

// ---- model load (fail-closed) ------------------------------------------------

const LIST_KEY_ORDER = ['domainInclude', 'domainExclude', 'ipInclude', 'ipExclude', 'ipBlock', 'autohostlist'];

function load_model() {
	let raw = readfile(PATHS.lists_model);
	if (!raw) return null;
	let m = null;
	try { m = json(raw); } catch (e) { return null; }
	if (type(m) != 'object' || m == null) return null;
	if (type(m.lists) != 'object' || m.lists == null) return null;
	for (let i = 0; i < length(LIST_KEY_ORDER); i++)
		if (type(m.lists[LIST_KEY_ORDER[i]]) != 'object') return null;
	return m;
}

const MODEL = load_model();

// ---- logic (mirrors tests/lib/lists-logic.mjs) ------------------------------
// ucode does NOT hoist `function` declarations in module mode (a helper must
// precede its first caller), so tolower is defined BEFORE normalize_domain.

// ucode has no built-in tolower/.lower(); map A-Z → a-z via ord/chr (no
// subprocess, no shell injection). ASCII only — domains are ASCII (IDN is
// punycode-encoded before it reaches here).
function tolower(s) {
	let out = '';
	for (let i = 0; i < length(s); i++) {
		let c = substr(s, i, 1);
		let code = ord(c);
		if (code >= 65 && code <= 90) c = chr(code + 32);   // 'A'..'Z' → 'a'..'z'
		out += c;
	}
	return out;
}

function normalize_domain(d) {
	if (d == null) return '';
	let s = trim('' + d);
	s = tolower(s);
	if (substr(s, 0, 1) == '.') s = substr(s, 1);
	return s;
}

function find_conflicts(include, exclude) {
	if (!include || !exclude) return [];
	let ex = {};
	for (let i = 0; i < length(exclude); i++) {
		let n = normalize_domain(exclude[i]);
		if (length(n)) ex[n] = true;
	}
	let conflicts = [];
	let seen = {};
	for (let i = 0; i < length(include); i++) {
		let n = normalize_domain(include[i]);
		if (!length(n) || seen[n]) continue;
		if (ex[n]) { push(conflicts, n); seen[n] = true; }
	}
	return conflicts;
}

// _in_list is declared BEFORE check_domain (ucode does not hoist `function`
// declarations in module mode — a helper must precede its first caller).
function _in_list(n, arr) {
	if (!arr) return false;
	for (let i = 0; i < length(arr); i++)
		if (normalize_domain(arr[i]) == n) return true;
	return false;
}

function check_domain(domain, lists) {
	let n = normalize_domain(domain);
	let inInc = _in_list(n, lists.userInclude);
	let inExc = _in_list(n, lists.userExclude);
	let inAuto = _in_list(n, lists.autohostlist);
	return {
		domain: n,
		userInclude: inInc,
		userExclude: inExc,
		autohostlist: inAuto,
		conflict: inInc && inExc
	};
}

// ---- mapping type validation (mirrors tests/lib/lists-model.mjs) ------------
// The semantic type of a KEY is fixed by the manager contract (domain keys
// hold hostnames, IP keys hold addresses). A write is refused when the model
// maps a key to the WRONG declared type — the shipped-defect class (a domain
// key pointed at an ipset file). tests/lists-model.test.mjs additionally
// cross-checks each declared type against the upstream path classification
// (hostlist files are domain lists, ipset files are IP lists), so a wrong
// declaration cannot slip through both sides.

function key_type(k) {
	if (k == 'domainInclude' || k == 'domainExclude' || k == 'autohostlist') return 'domain';
	if (k == 'ipInclude' || k == 'ipExclude' || k == 'ipBlock') return 'ip';
	return null;
}

// ---- state ------------------------------------------------------------------

// Read all list state through the model: editable user lists and read-only
// entries with explicit reasons. entries is null when the key has no proven
// path (nothing is invented). present marks on-disk existence for keys that
// have a path. Returns an object the UI renders directly.
export const lists_get = function() {
	if (MODEL == null)
		return { error: 'list model unavailable', generatedAt: null };
	let lists = {};
	for (let i = 0; i < length(LIST_KEY_ORDER); i++) {
		let k = LIST_KEY_ORDER[i];
		let spec = MODEL.lists[k];
		let entries = null;
		let present = false;
		if (spec.path != null) {
			present = stat(spec.path) ? true : false;
			entries = read_list_file(spec.path);
		}
		lists[k] = {
			entries: entries,
			path: spec.path,
			type: spec.type,
			editable: (spec.editable == true),
			engine: (spec.engine == true),
			present: present,
			reason: spec.reason
		};
	}
	return {
		schema: 2,
		lists: lists,
		provenance: MODEL.provenance,
		conflicts: find_conflicts(lists.domainInclude.entries, lists.domainExclude.entries)
	};
};

// Apply user list edits. WIRE FORMAT: `edit` is a JSON STRING (rpcd params are
// strings — the frontend sends edit as a JSON-encoded string). We parse it ONCE
// (no sprintf("%J") before parse, no double-encode), require an OBJECT whose
// keys exist in the MODEL: unknown keys, engine-owned keys, non-writable keys
// (unproven or generated — the response carries the model reason) and mapping
// type mismatches (a domain key mapped to an ipset file, or vice versa) are
// all refused BEFORE any write. Conflicts (a domain in BOTH include and
// exclude) are refused the same way. Each write goes through apply.uc
// write_list_file (single write path); a write failure is surfaced as
// {ok:false, error} (write_list_file returns null on failure). Mirrors
// tests/lib/lists-model.mjs validateEdit + tests/lib/lists-wire.mjs.
export const validate_edit = function(edit_str) {
	if (MODEL == null)
		return { ok: false, error: 'list model unavailable' };
	if (type(edit_str) != 'string')
		return { ok: false, error: 'edit must be a JSON string', got: type(edit_str) };
	let edit = null;
	try { edit = json(edit_str); } catch (e) { return { ok: false, error: 'invalid JSON' }; }
	// json() decodes an object to type 'object', an array to 'array', null to ''
	// (empty), numbers to 'int'. Require an object (rejects array/null/scalar).
	if (type(edit) != 'object')
		return { ok: false, error: 'edit must decode to an object' };
	let ks = keys(edit);
	if (length(ks) === 0)
		return { ok: false, error: 'edit must be a non-empty object' };
	for (let i = 0; i < length(ks); i++) {
		let k = ks[i];
		let spec = MODEL.lists[k];
		if (spec == null)
			return { ok: false, error: 'unknown list key: ' + k };
		if (spec.engine == true)
			return { ok: false, error: 'engine-owned list cannot be edited: ' + k };
		if (spec.editable != true)
			return { ok: false, error: 'list is not writable', list: k, reason: spec.reason };
		if (spec.path == null)
			return { ok: false, error: 'list has no proven path', list: k, reason: spec.reason };
		if (key_type(k) != null && spec.type != key_type(k))
			return { ok: false, error: 'mapping type mismatch', list: k, expected: key_type(k), got: spec.type };
		let v = edit[k];
		if (type(v) != 'array')
			return { ok: false, error: 'value for ' + k + ' must be an array' };
		for (let j = 0; j < length(v); j++) {
			if (type(v[j]) != 'string')
				return { ok: false, error: 'element ' + j + ' of ' + k + ' must be a string' };
		}
	}
	return { ok: true, edit: edit };
};

export const lists_set = function(edit_str) {
	let v = validate_edit(edit_str);
	if (!v.ok) return v;          // { ok:false, error, ... }
	let edit = v.edit;
	let conflicts = find_conflicts(edit.domainInclude, edit.domainExclude);
	if (length(conflicts) > 0) {
		return { ok: false, error: 'conflict',
			message: 'domains in BOTH include and exclude',
			conflicts: conflicts };
	}
	// write each present list through apply.uc write_list_file (single write
	// path) to its MODEL path — validate_edit has already proven the key
	// writable with a non-null path. write_list_file returns null on failure:
	// surface it, do NOT claim success.
	let written = [];
	for (let i = 0; i < length(LIST_KEY_ORDER); i++) {
		let k = LIST_KEY_ORDER[i];
		if (edit[k] == null) continue;
		let r = write_list_file(MODEL.lists[k].path, edit[k]);
		if (r == null)
			return { ok: false, error: 'write failed', list: k, written: written };
		push(written, k);
	}
	return { ok: true, written: written };
};

// Check whether a domain falls under the autohostlist or the user lists.
// The main user-confusion source: "I added a domain manually, but the auto-
// hostlist covers it, or vice versa."
export const lists_check_domain = function(domain) {
	if (MODEL == null)
		return { ok: false, error: 'list model unavailable' };
	let st = lists_get();
	return check_domain(domain, {
		userInclude: st.lists.domainInclude.entries,
		userExclude: st.lists.domainExclude.entries,
		autohostlist: st.lists.autohostlist.entries
	});
};
