'use strict';
// Persistent, user initiated strategy runner.  The worker is deliberately
// separate from orchestra.uc: zapret-auto.lua remains read-only here.

import { readfile, writefile, stat, mkdir, unlink, lsdir, popen } from 'fs';
import { load_state } from './profiles-draft.uc';
import { read_var } from './apply.uc';
import { profiles_apply_candidate } from './profiles-apply.uc';
import { z2m_parse, z2m_fragment } from './profiles.uc';
import { catalog_get, catalog_list, catalog_status } from './catalog.uc';

const ROOT = '/tmp/zapret2-manager/orchestra-runs';
const ACTIVE = ROOT + '/active.json';
const WORKER = '/usr/libexec/zapret2-manager/orchestra-worker.uc';
const ADAPTER = '/usr/libexec/zapret2-manager/orchestra-candidate-run.sh';
const PREFLIGHT = '/usr/libexec/zapret2-manager/orchestra-probe-preflight.sh';
const CORPUS = '/usr/libexec/zapret2-manager/catalog/orchestra-strategies.json';
const Z2GUI = '/usr/libexec/zapret2-manager/catalog/orchestra-zapret2gui.json';
const SERVICES = '/usr/libexec/zapret2-manager/services';
const MAX_HISTORY = 20, MAX_EVENTS = 500, LOG_LIMIT = 8192, MAX_SERVICE_DOMAINS = 16, MAX_SERVICE_ATTEMPTS = 600;
const PROTOCOLS = ['tcp_https', 'quic_udp'];
const TERMINAL = ['completed', 'applied', 'rolled-back', 'restored', 'timeout', 'timed-out', 'partial', 'infrastructure-error', 'cancelled', 'canceled', 'stopped', 'failed', 'interrupted'];
const APPLY_ROOT = '/var/lib/zapret2-manager/orchestra-operations';

function err(code, message, details, runId, phase) { return { ok:false, error:{ code:code, message:message, details:details || {}, runId:runId || null, phase:phase || null } }; }
function ensure() { try { mkdir('/tmp/zapret2-manager'); mkdir(ROOT); } catch(e) {} }
function safe_id(id) { return type(id) == 'string' && match(id, /^or-[a-f0-9]{8}-[a-f0-9]{4}$/); }
function path(id) { return ROOT + '/' + id + '.json'; }
function load(p) { try { let x = json(readfile(p)); return type(x) == 'object' ? x : null; } catch(e) { return null; } }
function lower(v) { let s = '' + (v || ''), out = ''; for (let i = 0; i < length(s); i++) { let n = ord(substr(s,i,1)); out += n >= 65 && n <= 90 ? chr(n + 32) : substr(s,i,1); } return out; }
function has(a, value) { for (let x in a) if (x == value) return true; return false; }
function hostname(v) {
	let d=lower(trim(v||'')); if(length(d)&&substr(d,length(d)-1,1)=='.')d=substr(d,0,length(d)-1);
	if(length(d)<3||length(d)>253||index(d,'.')<0)return null;
	let labels=split(d,'.'); for(let li=0;li<length(labels);li++){let label=labels[li];if(length(label)<1||length(label)>63||substr(label,0,1)=='-'||substr(label,length(label)-1,1)=='-')return null;for(let i=0;i<length(label);i++){let n=ord(substr(label,i,1));if(!((n>=97&&n<=122)||(n>=48&&n<=57)||n==45))return null;}}
	return d;
}
function sha256_text(text) { let p='/tmp/z2m-orchestra-sha.'+time();writefile(p,''+text);let q=popen("sha256sum '"+p+"' 2>/dev/null | awk '{print $1}'",'r'),h=q?trim(q.read('all')||''):'';if(q)q.close();try{unlink(p);}catch(e){}return h||null; }
function service_manifest(id) {
	if(type(id)!='string'||!match(id,/^[A-Za-z0-9_.-]{1,128}$/))return {ok:false,error:{code:'EINPUT',message:'invalid service id'}};
	let p=SERVICES+'/'+id+'.json',raw=readfile(p),doc=null;
	if(!raw)return {ok:false,error:{code:'ENOENT',message:'service manifest is not packaged',details:{serviceId:id}}};
	try{doc=json(raw);}catch(e){return {ok:false,error:{code:'ETARGET',message:'service manifest is invalid JSON'}};}
	if(type(doc)!='object'||doc.schema!=1||doc.serviceId!=id||type(doc.targets)!='array'||type(doc.requiredTargetIds)!='array')return {ok:false,error:{code:'ETARGET',message:'service manifest schema or serviceId is invalid'}};
	let seen={},targets=[];
	for(let t in doc.targets){
		if(type(t)!='object'||type(t.id)!='string'||type(t.domain)!='string'||t.protocol!='tcp_https'||!has(['https','websocket','bounded_download'],t.probe)||seen[t.id]||!hostname(t.domain))return {ok:false,error:{code:'ETARGET',message:'service manifest contains an invalid TCP target'}};
		seen[t.id]=true;
		push(targets,{id:t.id,domain:hostname(t.domain),protocol:t.protocol,protocols:[t.protocol],probe:t.probe,required:false});
	}
	for(let id2 in doc.requiredTargetIds){
		if(!seen[id2])return {ok:false,error:{code:'ETARGET',message:'required target is not declared',details:{targetId:id2}}};
		for(let target in targets)if(target.id==id2)target.required=true;
	}
	return {ok:true,manifest:{schema:1,serviceId:id,source:doc.source,requiredTargetIds:doc.requiredTargetIds,targets:targets,dnsChecks:doc.dnsChecks||[]},raw:raw,digest:sha256_text(raw)};
}
function service_progress(r, chosen) {
	if(r.targetType!='service')return;
	if(!r.targetProgress)r.targetProgress=[];
	for(let target in r.targets){let p=null;for(let old in r.targetProgress)if(old.targetId==target.id)p=old;if(!p){p={targetId:target.id,domain:target.domain,testedCandidateIds:[],nextCandidateIndex:0,attempts:0,rankedResults:[],winner:null,exhausted:false,failureReason:null};push(r.targetProgress,p);}let tested={};for(let a in r.results)if(a.domain==target.domain){tested[a.candidateId]=true;if(!has(p.testedCandidateIds,a.candidateId))push(p.testedCandidateIds,a.candidateId);}p.attempts=length(p.testedCandidateIds);p.nextCandidateIndex=length(chosen);for(let i=0;i<length(chosen);i++)if(!tested[chosen[i].id]){p.nextCandidateIndex=i;break;}}
}
function ctl(id, name) { return ROOT + '/' + id + '.' + name; }
function request_event(r,t,m) { if(!r.events)r.events=[];let n=length(r.events)?r.events[length(r.events)-1].sequence+1:1;push(r.events,{sequence:n,timestamp:time(),type:t,message:m,details:{}}); }
function clear_active_lock(id) {
	let a=load(ACTIVE);
	if(!a || a.runId!=id)return;
	try { unlink(ACTIVE); } catch(e) {}
}
export const clear_request_artifacts = function(id) {
	// Control artifacts are written by both rpcd and the worker.  Use one
	// id-scoped cleanup command after the terminal state has been saved.
	let base=ROOT+'/'+id;
	run("rm -f '"+base+".control' '"+base+".pause' '"+base+".stop'");
};
function request_save(r) { let p=path(r.runId),t=p+'.rpc.'+time();writefile(t,sprintf('%J',r)+'\n');let m=popen("mv -f '"+t+"' '"+p+"' 2>&1",'r');if(!m||m.close()!=0)return false;if(!has(TERMINAL,r.phase)&&worker_matches(r)){let a=ACTIVE+'.rpc.'+time();writefile(a,sprintf('%J',{runId:r.runId,pid:r.workerPid,workerStarttime:r.workerStarttime})+'\n');let q=popen("mv -f '"+a+"' '"+ACTIVE+"' 2>&1",'r');if(q)q.close();}else clear_active_lock(r.runId);return true; }
function control_path(id) { return ROOT + '/' + id + '.control'; }
export const control_load = function(id) {
	let c=load(control_path(id));
	return c && c.runId==id ? c : {runId:id,pauseRequested:false,stopRequested:false,revision:0,updatedAt:time()};
};
function control_save(c) {
	let p=control_path(c.runId), tmp=p+'.tmp.'+time();
	writefile(tmp,sprintf('%J',c)+'\n');
	let m=popen("mv -f '"+tmp+"' '"+p+"' 2>&1",'r'); return m && m.close()==0;
}
function control_request(r, command) {
	let terminal=has(TERMINAL,r.phase);
	if(command=='pause') {
		if(terminal || r.phase=='ranking' || r.phase=='applying' || r.phase=='stopping' || r.phase=='stopped') return err('ESTATE','pause is not valid in the current phase',{},r.runId,r.phase);
	} else if(command=='resume') {
		if(terminal || (!r.control.pauseRequested && r.phase!='paused')) return err('ESTATE','resume requires paused or pause-requested state',{},r.runId,r.phase);
	} else if(command=='stop') {
		if(r.phase=='stopped'||r.phase=='stopping') return {ok:true,run:r,idempotent:true};
		if(terminal) return err('ESTATE','stop is not valid after terminal completion',{},r.runId,r.phase);
	} else return err('EINPUT','unknown control command');
	let c=control_load(r.runId);
	if(command=='pause' && c.pauseRequested) return {ok:true,run:r,idempotent:true};
	if(command=='resume' && !c.pauseRequested && r.phase=='paused') return err('ESTATE','resume request is not pending',{},r.runId,r.phase);
	if(command=='stop' && c.stopRequested) return {ok:true,run:r,idempotent:true};
	if(command=='pause') c.pauseRequested=true;
	if(command=='resume') c.pauseRequested=false;
	if(command=='stop') c.stopRequested=true;
	c.revision=(c.revision||0)+1;c.updatedAt=time();
	if(!control_save(c)) return err('EIO','could not atomically update control state',{},r.runId,r.phase);
	r.control=c;
	request_event(r,command=='pause'?'pause-requested':command=='resume'?'resume-requested':'stop-requested',command=='pause'?'Pause requested':command=='resume'?'Resume requested':'Stop requested; worker cleanup pending');
	request_save(r);
	return {ok:true,run:r};
}
export const run = function(cmd) { let p = popen(cmd + ' 2>&1', 'r'); if (!p) return {out:'',rc:-1}; let out=p.read('all') || ''; return {out:out,rc:p.close()}; };
export const orchestra_probe_preflight = function() {
	let x=run("'"+PREFLIGHT+"'");
	try { let parsed=json(x.out); if(type(parsed)=='object'&&parsed.ok===true)return parsed; if(type(parsed)=='object'&&parsed.ok===false)return parsed; } catch(e) {}
	return {ok:false,error:{code:'EPROBEDEPENDENCY',message:'probe preflight did not return structured JSON',details:{rc:x.rc,output:substr(x.out||'',0,2048)}}};
};
function pid_alive(pid) { return type(pid) == 'int' && pid > 1 && run('kill -0 ' + pid + ' 2>/dev/null').rc == 0; }
export const proc_starttime = function(pid) { let raw=readfile('/proc/'+pid+'/stat'); if(!raw)return null; let f=split(trim(raw),' '); return length(f)>21 ? f[21] : null; };
function worker_matches(r) { return r && r.workerPid && r.workerStarttime && pid_alive(r.workerPid) && proc_starttime(r.workerPid)==r.workerStarttime; }
export const add_event = function(r,type,message,details) { if (!r.events) r.events=[]; let n=length(r.events)?r.events[length(r.events)-1].sequence+1:1; push(r.events,{sequence:n,timestamp:time(),type:type,message:message,details:details||{}}); if(length(r.events)>MAX_EVENTS)r.events=slice(r.events,length(r.events)-MAX_EVENTS); };
export const save = function(r) {
	if(r&&r.targetType=='service'&&r.phase=='completed'&&type(r.serviceVerdict)=='object'){r.targetResults=r.serviceResults||[];for(let tp in r.targetProgress||[])if(!tp.winner){tp.exhausted=true;tp.failureReason='no-winner';}r.continuable=false;for(let tg in r.targetResults){for(let mt in r.targets)if(mt.domain==tg.domain)tg.targetId=mt.id;for(let pp in tg.protocols||[])if(pp.winner){pp.winner.positiveEvidenceIds=[];for(let ev in pp.winner.evidence||[])if(ev.positiveEvidence)push(pp.winner.positiveEvidenceIds,r.runId+'-e-'+ev.candidateId+'-'+ev.attempt);}}r.serviceVerdict=(r.serviceVerdict.domainsWithConfirmedWinner==length(r.targets))?'ready':(r.serviceVerdict.domainsWithoutWinner>0?'failed':'indeterminate');r.applyAllowed=r.serviceVerdict=='ready';}
	ensure(); let tmp=path(r.runId)+'.tmp.'+time()+'.'+(r.workerPid || 0); writefile(tmp, sprintf('%J',r)+'\n');
	let mv=run("mv -f '" + tmp + "' '" + path(r.runId) + "'"); if (mv.rc != 0) return false;
	if (!has(TERMINAL,r.phase) && worker_matches(r)) { let a=ACTIVE+'.tmp.'+time(); writefile(a,sprintf('%J',{runId:r.runId,pid:r.workerPid,workerStarttime:r.workerStarttime})+'\n'); run("mv -f '"+a+"' '"+ACTIVE+"'"); }
	else clear_active_lock(r.runId);
	return true;
};
function reconcile_active(r) { if(!r||has(TERMINAL,r.phase)||worker_matches(r))return r; r.phase='interrupted';r.finishedAt=time();r.error={code:'EINTERRUPTED',message:'worker process is no longer alive or no longer matches its recorded starttime',details:{workerPid:r.workerPid||null,workerStarttime:r.workerStarttime||null}};r.cleanup={status:'completed',reason:'owned worker identity missing or changed',checkedAt:time(),workerPid:r.workerPid||null,workerStarttime:r.workerStarttime||null};add_event(r,'interrupted','Recovered stale worker lock',r.error.details);save(r);clear_request_artifacts(r.runId);return null; }
function active() { let a=load(ACTIVE); if (!a || !safe_id(a.runId)) return null; let r=load(path(a.runId)); if (!r) { clear_active_lock(a.runId); return null; } return reconcile_active(r); }
function payload_for(line) { for(let t in split(trim(line),' '))if(substr(t,0,10)=='--payload=')return substr(t,10);return null; }
function corpus_hash(text) { let p='/tmp/zapret2-manager/orchestra-corpus-hash.'+time();writefile(p,''+text);let h=trim(run("sha256sum '"+p+"' 2>/dev/null | awk '{print $1}'").out);try{unlink(p);}catch(e){}return h||null; }
export const corpus_translate = function(opt) { let out=[],removed=[],raw=''+opt,quote=0;for(let i=0;i<length(raw);i++){let ch=substr(raw,i,1);if(ch==chr(34)||ch=="'")quote=quote?0:1;}if(quote)return{ok:false,reason:'malformed quoting'};for(let token in split(trim(raw),' ')){if(!length(token))continue;if(token=='<HOSTLIST>'||token=='<HOSTLIST_NOAUTO>'||substr(token,0,9)=='--filter-'||substr(token,0,10)=='--hostlist'||substr(token,0,10)=='--comment='||token=='--comment'||substr(token,0,6)=='--new='||token=='--new'){push(removed,token);continue;}if(index(token,'<')>=0||index(token,'>')>=0)return{ok:false,reason:'unresolved placeholder'};push(out,token);}let line=join(' ',out);if(!length(line)||(index(line,'--payload')<0&&index(line,'--lua-desync')<0))return{ok:false,reason:'no upstream strategy parameters'};return{ok:true,input:line,removed:removed,hash:corpus_hash(line)}; };
function corpus_profiles() {
	let doc=load(CORPUS),out=[];if(!doc||doc.schema!=1||type(doc.sources)!='array')return {profiles:out,revision:'missing'};
	for(let src in doc.sources){if(type(src.source)!='string'||type(src.sourceRevision)!='string'||type(src.protocol)!='string'||type(src.lines)!='array')continue;for(let raw in src.lines){let meta=corpus_translate(raw);if(!meta.ok)continue;let payload=payload_for(meta.input);if((src.protocol=='tcp_https'&&payload!='tls_client_hello')||(src.protocol=='quic_udp'&&payload!='quic_initial'))continue;let id='c-'+substr(corpus_hash(src.source+'\n'+src.sourceRevision+'\n'+src.protocol+'\n'+meta.input),0,16);push(out,{id:id,name:src.sourcePath+' · '+src.protocol+' · '+substr(meta.input,0,48),displayName:src.sourcePath+' · '+src.protocol,opt:meta.input,revision:src.sourceRevision,canonicalStrategyId:id,upstreamStrategyReference:src.source+':'+src.sourcePath+'@'+src.sourceRevision,source:src.source,sourcePath:src.sourcePath,protocols:[src.protocol],protocol:src.protocol,compatibilityStatus:'compatible',unsupportedReason:null,sanitizedParameterHash:meta.hash,removedManagerOnlyOptions:meta.removed});}}
	return {profiles:out,revision:doc.catalogRevision||'unknown'};
}
export const profile_set = function(ids,mode) {
	let s=load_state(),out=[],seen={};if(!s.ok)return null;let cp=corpus_profiles(),zdoc=load(Z2GUI),zrevision=zdoc&&zdoc.sourceRevision||'missing';
	if(mode!='zapret2gui-only')for(let c in cp.profiles){if(!ids||ids[c.id]){push(out,c);seen[c.sanitizedParameterHash]=true;}}
	if(zdoc&&type(zdoc.candidates)=='array')for(let z in zdoc.candidates){if(z.compatibilityStatus!='compatible'||type(z.parameters)!='string')continue;let h=z.normalizedParameterHash||corpus_hash(z.parameters),ref={source:'zapret2gui',sourcePath:z.sourcePath,sourceRevision:z.sourceRevision,preset:z.preset,generator:z.generator};if(seen[h]){for(let c in out)if(c.sanitizedParameterHash==h){if(!c.sourceReferences)c.sourceReferences=[];push(c.sourceReferences,ref);}continue;}let c={id:z.id,name:z.name||z.id,displayName:z.name||z.id,opt:z.parameters,revision:z.sourceRevision||zrevision,canonicalStrategyId:z.id,upstreamStrategyReference:'zapret2gui:'+z.sourcePath+'#'+z.generator+'@'+z.sourceRevision,source:'zapret2gui',sourcePath:z.sourcePath,protocols:[z.protocol],protocol:z.protocol,recommended:z.label=='recommended',compatibilityStatus:'compatible',unsupportedReason:null,sanitizedParameterHash:h,removedManagerOnlyOptions:[],requiredLuaFunctions:z.requiredLuaFunctions||[],requiredBlobs:z.requiredBlobs||[],sourceReferences:[ref]};if(!ids||ids[c.id]){push(out,c);seen[h]=true;}}
	for(let p in s.state.profiles){if(type(p.id)!='string'||type(p.opt)!='string'||!match(p.id,/^p[0-9]{6}$/))continue;let meta=corpus_translate(p.opt),payload=meta.ok?payload_for(meta.input):null;if(!meta.ok||!payload)continue;if(seen[meta.hash])continue;let protocol=payload=='quic_initial'?'quic_udp':payload=='tls_client_hello'?'tcp_https':payload=='http_req'?'tcp_http':'unsupported';let c={id:p.id,name:p.name||p.id,opt:meta.input,revision:p.revision||1,canonicalStrategyId:p.id,upstreamStrategyReference:'manager-profile:'+p.id+'@'+(p.revision||1),source:'manager-profile',sourcePath:'/etc/zapret2-manager/state.json',protocols:[protocol],protocol:protocol,compatibilityStatus:protocol=='unsupported'?'unsupported':'compatible',unsupportedReason:protocol=='unsupported'?'payload is not a supported Blockcheck protocol':null,sanitizedParameterHash:meta.hash,removedManagerOnlyOptions:meta.removed};if(!ids||ids[p.id]){push(out,c);seen[meta.hash]=true;}}
	let filtered=[];for(let c in out)if((!ids||ids[c.id])&&(mode!='zapret2gui-only'||c.source=='zapret2gui'))push(filtered,c);out=filtered;
	for(let i=1;i<length(out);i++){let x=out[i],j=i-1,rank=mode=='recommended'?(x.source=='zapret2gui'?(x.recommended?0:1):2):0;while(j>=0){let jr=mode=='recommended'?(out[j].source=='zapret2gui'?(out[j].recommended?0:1):2):0;if(jr<rank||(jr==rank&&out[j].id<=x.id))break;out[j+1]=out[j];j--;}out[j+1]=x;}
	return {profiles:out,revision:cp.revision+'+z2gui-'+zrevision+'+profiles-'+(s.state.updatedAt||0)};
};
function registry_snapshot() {
	let ps=profile_set(null,'zapret2gui-only'), text='', ids=[];
	if(!ps)return null;
	for(let c in ps.profiles)if(c.protocol=='tcp_https'){text+=(text?'\n':'')+c.id+'\t'+c.opt;push(ids,c.id);}
	return {profiles:ps.profiles,ids:ids,digest:sha256_text(text),revision:ps.revision};
}
function hash_text(text) { let p='/tmp/zapret2-manager/orchestra-hash.'+time(); writefile(p,''+text); let h=trim(run("sha256sum '"+p+"' 2>/dev/null | awk '{print $1}'").out); try{unlink(p);}catch(e){} return h||null; }
export const translate_strategy = function(opt) { let out=[],removed=[]; let raw=''+opt, quote=0; for(let i=0;i<length(raw);i++){let ch=substr(raw,i,1);if(ch==chr(34)||ch=="'")quote=quote?0:1;} if(quote)return{ok:false,reason:'malformed quoting'}; for(let token in split(trim(raw),' ')){ if(!length(token))continue; if(token=='<HOSTLIST>'||token=='<HOSTLIST_NOAUTO>'||substr(token,0,9)=='--filter-'||substr(token,0,10)=='--hostlist'||substr(token,0,10)=='--comment='||token=='--comment'||substr(token,0,6)=='--new='||token=='--new'){if(token!='<HOSTLIST>'&&token!='<HOSTLIST_NOAUTO>')push(removed,token);continue;} if(index(token,'<')>=0||index(token,'>')>=0)return{ok:false,reason:'unresolved placeholder'}; push(out,token); } let line=join(' ',out); if(!length(line)||(index(line,'--payload')<0&&index(line,'--lua-desync')<0))return{ok:false,reason:'no upstream strategy parameters'}; return{ok:true,input:line,removed:removed,hash:hash_text(line)}; };
export const bounded = function(s) { s=''+(s||''); return length(s)>LOG_LIMIT?substr(s,length(s)-LOG_LIMIT):s; };
function positive_marker(text,testName,domain,resolved) { if(index(text,'PROBE_FAIL')>=0)return false; let want=join(' ',split(trim(resolved||''),' ')),wantLow=lower(want);for(let line in split(text,'\n')){let s=trim(line),prefix='!!!!! '+testName+': working strategy found for ipv',needle=' '+lower(domain)+' : nfqws2 ';if(index(lower(s),lower(prefix))!=0||index(lower(s),needle)<0||substr(s,length(s)-5)!='!!!!!')continue;let at=index(lower(s),needle);let params=join(' ',split(trim(substr(s,at+length(needle),length(s)-at-length(needle)-5)),' '));if(!want||lower(params)==wantLow)return true;}return false; }

export const classify_attempt = function(r,c,proto,attempt,started,finished,rc,log,timed,reference,resolved,meta,target) {
	let domain=target||r.target,text=bounded(log), errors=[], parameterErrors=[]; if(match(text,/command not found/i))push(errors,'command not found'); if(match(text,/permission denied/i))push(errors,'permission denied'); if(match(text,/syntax error/i))push(errors,'syntax error'); if(match(text,/no such file/i))push(errors,'no such file'); if(match(text,/cannot create/i))push(errors,'cannot create'); if(match(text,/failed to execute/i))push(errors,'failed to execute'); if(match(text,/unknown option/i))push(parameterErrors,'unknown option'); if(match(text,/unrecognized option/i))push(parameterErrors,'unrecognized option'); if(match(text,/invalid argument/i))push(parameterErrors,'invalid argument'); if(match(text,/failed to parse/i))push(parameterErrors,'failed to parse'); if(match(text,/invalid value/i))push(parameterErrors,'invalid value');
	let testName=proto=='tcp_https'?'curl_test_https_tls12':'curl_test_http3', low=lower(text), lowDomain=lower(domain), startedEvidence=index(low,lower(testName+' ipv'))>=0||index(low,lower(testName+':'))>=0, positive=positive_marker(text,testName,domain,resolved);
	let normalNegative=(index(low,lower('strategy for ipv4 '+domain+' not found'))>=0||index(low,lower('strategy for ipv6 '+domain+' not found'))>=0||index(low,lower(domain+' : nfqws2 not working'))>=0||match(text,/UNAVAILABLE( code=[0-9]+)?/i)), supported=!(proto=='quic_udp'&&match(text,/does not support http3|tests disabled/i));
	let verdict='indeterminate', reason='no recognized positive or target result marker'; if(!meta||!meta.ok){verdict='candidate-invalid';reason=meta?meta.reason:'trusted candidate resolution failed';} else if(!supported){verdict='unsupported';reason='installed curl does not support HTTP/3';} else if(timed||rc==124){verdict='timeout';reason='upstream custom test timed out';} else if(length(parameterErrors)){verdict='candidate-invalid';reason='nfqws2 rejected the sanitized parameters';} else if(rc==66||rc<0||length(errors)){verdict='runner-error';reason=length(errors)?'Blockcheck infrastructure failed':'Blockcheck executable or result channel unavailable';} else if(positive){verdict='pass';reason='upstream Blockcheck reported a working strategy';} else if(startedEvidence&&normalNegative){verdict='target-fail';reason='upstream Blockcheck completed without a working strategy';} else if(!startedEvidence){verdict='indeterminate';reason='target test start could not be proven';} else if(rc!=0){verdict='runner-error';reason='upstream Blockcheck exited '+rc;}
	return {domain:domain,candidateId:c.id,canonicalStrategyId:c.canonicalStrategyId,displayName:c.displayName||c.name,source:c.source||'manager-profile',sourcePath:c.sourcePath||null,protocol:proto,protocols:c.protocols||[proto],compatibilityStatus:c.compatibilityStatus||'compatible',unsupportedReason:c.unsupportedReason||null,attempt:attempt,startedAt:started,finishedAt:finished,durationMs:(finished-started)*1000,supported:supported,passed:verdict=='pass',timedOut:timed,executionRc:rc,exitCode:rc,verdict:verdict,reason:reason,upstreamResult:positive?'pass':normalNegative?'target-fail':null,positiveEvidence:positive,errorMarkers:errors,parameterErrors:parameterErrors,candidateResolved:!!(meta&&meta.ok),resolvedStrategyReference:reference,upstreamCustomInput:resolved,evidence:{source:'upstream blockcheck2.sh',candidateName:c.name},testStarted:startedEvidence,upstreamSummary:positive?'working strategy found':normalNegative?'strategy not found / not working':null,sanitizedParameterHash:meta?meta.hash:null,removedManagerOnlyOptions:meta?meta.removed:[],catalogRevision:c.revision,boundedLog:text,cleanup:{status:'completed'}};
	};

export const orchestra_run_validate = function(input) {
	if(type(input)!='object'||input==null)return err('EINPUT','start requires an object');
	if(input.targetType!='domain'&&input.targetType!='service')return err('EINPUT','targetType must be domain or service');
	let target=input.targetType=='domain'?hostname(input.domain):trim(input.targetId||''); if(!target||(input.targetType=='service'&&!match(target,/^[A-Za-z0-9_.-]{1,128}$/)))return err('EINPUT','target must be a hostname or trusted service id');
	let protocols=input.targetType=='service'?['tcp_https']:input.protocols;
	if(type(protocols)!='array'||!length(protocols))return err('EINPUT','at least one protocol is required'); for(let p in protocols)if(!has(PROTOCOLS,p))return err('EINPUT','protocols contain an unsupported value');
	let mode=input.candidateMode||(input.targetType=='service'?'zapret2gui-only':'recommended'), repeats=+(input.repeats||2), timeout=+(input.perAttemptTimeoutSec||20), total=+(input.totalTimeoutSec||600); if(!has(['recommended','all','selected','zapret2gui-only'],mode)||repeats<1||repeats>3||timeout<1||timeout>120||total<timeout||total>1800)return err('EINPUT','candidate selection or timeout is outside safe bounds');
	if(input.targetType=='service'&&(mode!='zapret2gui-only'||(type(input.candidateIds)=='array'&&length(input.candidateIds))))return err('EINPUT','service runs require registry-backed zapret2gui-only selection without candidateIds');
	if(mode=='selected'&&(type(input.candidateIds)!='array'||!length(input.candidateIds)))return err('EINPUT','selected mode needs candidateIds');
	let retryOf=input.retryOfRunId||null;if(retryOf&&!safe_id(retryOf))return err('EINPUT','retryOfRunId is invalid');
	return {ok:true,value:{targetType:input.targetType,target:target,protocols:protocols,candidateMode:mode,candidateIds:input.candidateIds||[],repeats:repeats,perAttemptTimeoutSec:timeout,totalTimeoutSec:total,retryOfRunId:retryOf}};
};
export const orchestra_run_start = function(input) {
	let v=orchestra_run_validate(input); if(!v.ok)return v; if(active())return err('EBUSY','an orchestration run is already active');
	let nonce=sprintf('%04x',(time()*1103515245)&0xffff), id='or-'+sprintf('%08x',time())+'-'+nonce, x=v.value;
	let service=null, targets=[], catalogVersion=null, catalogDigest=null, manifestDigest=null;
	if(x.targetType=='service'){
		if(x.retryOfRunId){let previous=load(path(x.retryOfRunId));if(!previous||previous.validity!='invalid')return err('ESTATE','retryOfRunId must reference an invalidated run');if(previous.serviceId!=x.target)return err('EINPUT','retry lineage service mismatch');}
		let sm=service_manifest(x.target);if(!sm.ok)return err(sm.error.code,sm.error.message,sm.error.details);
		service=sm.manifest;manifestDigest=sm.digest;for(let t in service.targets){t.protocols=[t.protocol];push(targets,t);}
	}
	let r={runId:id,createdAt:time(),startedAt:null,heartbeatAt:time(),phase:'queued',target:x.target,targetType:x.targetType,serviceId:service&&service.serviceId||null,retryOfRunId:x.retryOfRunId||null,validity:'valid',candidateEvidenceUsable:true,applyAllowed:false,invalidationReason:null,manifestDigest:manifestDigest,candidateRegistryDigest:null,candidateIds:x.candidateIds,candidateMode:x.candidateMode,protocols:x.protocols,repeats:x.repeats,perAttemptTimeoutSec:x.perAttemptTimeoutSec,totalTimeoutSec:x.totalTimeoutSec,currentTargetId:null,currentDomain:null,currentProtocol:null,currentCandidate:null,currentAttempt:null,candidatePid:null,candidateStarttime:null,completedCount:0,totalCount:null,totalCandidates:null,totalAttempts:null,progress:0,results:[],baselineEvidence:[],targetCandidateEvidence:[],diagnosticEvents:[],infrastructureErrorCount:0,rankedResults:[],serviceResults:[],targetResults:[],targets:targets,targetProgress:[],serviceVerdict:null,selectedWinner:null,continuationCount:0,continuable:false,sessionDeadline:null,preflight:null,events:[],error:null,cleanup:{status:'pending'},control:{runId:id,pauseRequested:false,stopRequested:false,revision:0,updatedAt:time()},workerPid:null,workerStarttime:null,appliedOperationId:null};
	add_event(r,'queued','Orchestration queued'); ensure(); try { mkdir(ROOT+'/'+id); } catch(e) {} if(!stat(ROOT+'/'+id))return err('EIO','could not create run runtime directory'); if(!control_save(r.control)||!save(r))return err('EIO','could not atomically save run');
	let spawned=run("sh -c '/usr/bin/ucode "+WORKER+" "+id+" >/dev/null 2>&1 & echo $!'"); let pid=+trim(spawned.out), start=proc_starttime(pid);
	if(spawned.rc!=0||!pid_alive(pid)||!start){r.phase='failed';r.finishedAt=time();r.error={code:'EIO',message:'could not start orchestration worker',details:{rc:spawned.rc,pid:pid||null}};r.cleanup={status:'completed',reason:'worker spawn failed'};add_event(r,'failed','Could not start orchestration worker',r.error.details);save(r);clear_request_artifacts(id);return err('EIO','could not start orchestration worker',r.error.details,id,r.phase);}
	r.workerPid=pid;r.workerStarttime=start;r.heartbeatAt=time();if(!save(r))return err('EIO','could not publish active worker state',{},id,r.phase);return {ok:true,run:r};
};
export const orchestra_run_load = function(input){let id=input&&input.runId;return safe_id(id)?load(path(id)):null;};
export const orchestra_run_status = function(input){active();let r=input&&input.runId?orchestra_run_load(input):active();return r?{ok:true,run:r}:err('ENOENT','run not found');};
export const orchestra_run_events = function(input){let r=orchestra_run_load(input)||active();if(!r)return err('ENOENT','run not found');let c=+(input&&input.cursor||0),a=[];for(let e in r.events)if(e.sequence>c)push(a,e);return{ok:true,runId:r.runId,events:a,nextCursor:length(r.events)?r.events[length(r.events)-1].sequence:c};};
export const orchestra_run_pause = function(){let r=active();return r?control_request(r,'pause'):err('ENOENT','no active run');};
export const orchestra_run_resume = function(){let r=active();return r?control_request(r,'resume'):err('ENOENT','no active run');};
export const orchestra_run_stop = function(){let r=active();return r?control_request(r,'stop'):err('ENOENT','no active run');};
export const orchestra_run_continue = function(input){
	if(type(input)!='object'||!safe_id(input.runId))return err('EINPUT','runId is required');
	let seconds=+(input.additionalTimeoutSec||0);if(seconds<1||seconds>1800)return err('EINPUT','additionalTimeoutSec must be between 1 and 1800',{},input.runId);
	let r=orchestra_run_load(input);if(!r)return err('ENOENT','run not found',{},input.runId);
	if(r.phase!='partial'&&r.phase!='timed-out'&&r.phase!='stopped'&&r.phase!='interrupted')return err('ESTATE','only partial, timed-out, stopped, or interrupted service runs can continue',{},r.runId,r.phase);
	if(r.targetType!='service')return err('EINPUT','continuation requires a service run',{},r.runId,r.phase);
	if(worker_matches(r)||active())return err('EBUSY','run already has an active worker',{},r.runId,r.phase);
	let sm=service_manifest(r.serviceId);if(!sm.ok)return err(sm.error.code,sm.error.message,sm.error.details,r.runId,r.phase);
	if(sm.digest!=r.manifestDigest)return err('ESTALE','service manifest digest changed',{expected:r.manifestDigest,actual:sm.digest},r.runId,r.phase);
	let snap=registry_snapshot();if(!snap||snap.digest!=r.candidateRegistryDigest)return err('ESTALE','candidate registry digest changed',{expected:r.candidateRegistryDigest,actual:snap&&snap.digest||null},r.runId,r.phase);
	r.targets=sm.manifest.targets;for(let t in r.targets)t.protocols=[t.protocol];service_progress(r,snap.profiles);
	r.phase='queued';r.continuationCount=(r.continuationCount||0)+1;r.continuable=false;r.sessionDeadline=time()+seconds;r.additionalTimeoutSec=seconds;r.finishedAt=null;r.error=null;r.cleanup={status:'pending'};r.workerPid=null;r.workerStarttime=null;r.currentTargetId=null;r.currentDomain=null;r.currentCandidate=null;r.currentAttempt=null;r.control=control_load(r.runId);r.control.pauseRequested=false;r.control.stopRequested=false;r.control.revision=(r.control.revision||0)+1;r.control.updatedAt=time();if(!control_save(r.control))return err('EIO','could not reset continuation controls',{},r.runId,r.phase);add_event(r,'continued','Bounded service scan continued',{additionalTimeoutSec:seconds,continuationCount:r.continuationCount});save(r);
	let spawned=run("sh -c '/usr/bin/ucode "+WORKER+" "+r.runId+" >/dev/null 2>&1 & echo $!'");let pid=+trim(spawned.out),start=proc_starttime(pid);if(spawned.rc!=0||!pid_alive(pid)||!start){r.phase='partial';r.continuable=true;r.cleanup={status:'completed',reason:'worker spawn failed'};r.error={code:'EIO',message:'could not start continuation worker'};save(r);return err('EIO','could not start continuation worker',{},r.runId,r.phase);}r.workerPid=pid;r.workerStarttime=start;save(r);return{ok:true,run:r};
};
function history_summary(r) { let w=r.selectedWinner||null, score=null;for(let x in r.rankedResults||[])if(w&&x.candidateId==w.candidateId){score=x.score;break;}return{runId:r.runId,createdAt:r.createdAt||null,startedAt:r.startedAt||null,finishedAt:r.finishedAt||null,phase:r.phase||null,target:r.target||null,targetType:r.targetType||null,protocols:r.protocols||[],candidateMode:r.candidateMode||null,candidateCount:r.totalCandidates||length(r.candidateIds||[]),completedCount:r.completedCount||0,totalCount:r.totalCount||null,winnerCandidateId:w&&w.candidateId||null,winnerScore:score,appliedOperationId:r.appliedOperationId||null,errorCode:r.error&&r.error.code||null}; }
export const orchestra_run_history = function(){ensure();active();let out=[];for(let n in (lsdir(ROOT)||[]))if(match(n,/^or-[a-f0-9]{8}-[a-f0-9]{4}\.json$/)){let r=load(ROOT+'/'+n);if(r)push(out,history_summary(r));}for(let i=0;i<length(out);i++)for(let j=i+1;j<length(out);j++)if(out[j].createdAt>out[i].createdAt){let t=out[i];out[i]=out[j];out[j]=t;}return{ok:true,runs:slice(out,0,10),limit:10,maxLimit:20};};
export const orchestra_run_delete = function(input){let r=orchestra_run_load(input);if(!r)return err('ENOENT','run not found');if(!has(TERMINAL,r.phase))return err('EBUSY','cannot delete active run');try{unlink(path(r.runId));}catch(e){return err('EIO','could not delete run');}return{ok:true,runId:r.runId};};
export const orchestra_run_invalidate = function(input){let r=orchestra_run_load(input);if(!r)return err('ENOENT','run not found');if(r.targetType!='service')return err('EINPUT','only service runs can be invalidated',{},r.runId,r.phase);if(worker_matches(r)||active())return err('EBUSY','cannot invalidate an active run',{},r.runId,r.phase);if(r.validity=='invalid')return{ok:true,idempotent:true,run:r};let raw=r.results||[];r.rawEvidence=raw;r.baselineEvidence=r.baselineEvidence||[];for(let e in raw)push(r.baselineEvidence,{source:'invalidated-run',reason:'EPROBEDEPENDENCY: suitable netcat not found',record:e});r.results=[];r.targetCandidateEvidence=[];r.validity='invalid';r.phase='infrastructure-error';r.invalidationReason='EPROBEDEPENDENCY: suitable netcat not found';r.candidateEvidenceUsable=false;r.applyAllowed=false;r.continuable=false;r.serviceVerdict=null;r.error={code:'EPROBEDEPENDENCY',message:'invalidated poisoned run: suitable netcat not found',details:{rawEvidenceCount:length(raw)}};r.cleanup={status:'completed',reason:'invalidated historical run',checkedAt:time()};add_event(r,'invalidated','Historical service run invalidated because probe transport was unavailable',r.error.details);save(r);return{ok:true,run:r};};
function corpus_inventory() { let doc=load(CORPUS),sourceCounts={},rejected=[],rawCount=0; if(doc&&type(doc.sources)=='array')for(let src in doc.sources){sourceCounts[src.source]=(sourceCounts[src.source]||0)+length(src.lines||[]);for(let raw in (src.lines||[])){rawCount++;let m=corpus_translate(raw);if(!m.ok&&trim(raw)&&substr(trim(raw),0,1)!='#')push(rejected,{source:src.source,sourcePath:src.sourcePath,reason:m.reason});}} return {rawCount:rawCount,sourceCounts:sourceCounts,rejected:rejected,catalogRevision:doc&&doc.catalogRevision||'missing'}; }
export const orchestra_run_capabilities = function(){let inv=corpus_inventory(),ps=profile_set(null,'all'),byProtocol={},sources={},zd=load(Z2GUI),zc=[],zrej=[],https=0,quic=0,allReject=[];if(ps)for(let c in ps.profiles){sources[c.source]=(sources[c.source]||0)+1;if(c.protocol=='tcp_https'||c.protocol=='quic_udp')byProtocol[c.protocol]=(byProtocol[c.protocol]||0)+1;}for(let e in inv.rejected)push(allReject,e);if(zd&&type(zd.candidates)=='array')for(let z in zd.candidates){push(zc,z);if(z.compatibilityStatus!='compatible'){let why={candidateId:z.id,reason:z.rejectionReason||'incompatible'};push(zrej,why);push(allReject,why);}else if(z.protocol=='tcp_https')https++;else if(z.protocol=='quic_udp')quic++;}return{ok:true,terminalPhases:TERMINAL,totalCandidates:ps?length(ps.profiles):0,compatibleByProtocol:byProtocol,sourceCounts:sources,corpusRawCount:inv.rawCount,rejectedCount:length(allReject),rejectionReasons:allReject,catalogRevision:inv.catalogRevision,zapret2gui:{total:length(zc),compatible:length(zc)-length(zrej),incompatible:length(zrej),https:https,quic:quic,deduplicated:zd?zd.rawDefinitionCount-length(zc):0,rejectionReasons:zrej,sourceRevision:zd&&zd.sourceRevision||'missing'},profileRevision:ps?ps.revision:null};};
function apply_path(id) { return APPLY_ROOT+'/'+id+'.json'; }
function apply_save(o) { try { mkdir('/var/lib/zapret2-manager'); mkdir(APPLY_ROOT); } catch(e) {} let p=apply_path(o.operationId),t=p+'.tmp.'+time();writefile(t,sprintf('%J',o)+'\n');return run("mv -f '"+t+"' '"+p+"'").rc==0; }
function apply_load(id) { return type(id)=='string' && match(id,/^op-[a-f0-9]{8}-[a-f0-9]{4}$/) ? load(apply_path(id)) : null; }
function apply_event(o,phase,message,details) { o.phase=phase;o.updatedAt=time();if(!o.events)o.events=[];push(o.events,{sequence:length(o.events)+1,timestamp:time(),phase:phase,message:message,details:details||{}}); }
function resolve_winner(r, input) {
	if(type(input)=='string')input={candidateId:input};
	if(!r)return err('ENOENT','run not found');if(r.targetType=='service')return err('EUNSUPPORTED','Apply supports domain runs only',{targetType:r.targetType},r.runId,r.phase);if(r.phase!='completed')return err('ESTATE','a completed run with a winner is required',{},r.runId,r.phase);let domain=r.target,protocol=input&&input.protocol||'tcp_https',winner=r.selectedWinner;if(input&&input.targetDomain&&input.targetDomain!=domain)return err('EINPUT','targetDomain does not match the immutable run snapshot',{},r.runId,r.phase);
	if(protocol!='tcp_https')return err('EUNSUPPORTED','Apply supports only tcp_https', {protocol:protocol},r.runId,r.phase);let id=input&&input.candidateId||winner&&winner.candidateId;if(!winner||id!=winner.candidateId)return err('EINPUT','candidateId is not the confirmed winner for this domain and protocol',{},r.runId,r.phase);let wanted={};wanted[id]=true;let ps=profile_set(wanted,'all');if(!ps||length(ps.profiles)!=1)return err('ESTALE','trusted winner is no longer in the catalog',{},r.runId,r.phase);let c=ps.profiles[0];if(c.protocol!='tcp_https')return err('EUNSUPPORTED','Apply supports only tcp_https',{protocol:c.protocol},r.runId,r.phase);let evidence=[];for(let a in r.results||[])if(a.domain==domain&&a.candidateId==id&&a.protocol=='tcp_https'&&a.verdict=='pass'&&a.positiveEvidence)push(evidence,a);if(length(evidence)<2)return err('EEVIDENCE','two real positive HTTPS attempts are required',{positiveEvidenceCount:length(evidence)},r.runId,r.phase);let normalized=translate_strategy(c.opt),positive=evidence[0];if(!normalized.ok||normalized.hash!=positive.sanitizedParameterHash)return err('ESTALE','candidate hash changed since the completed run',{expected:positive.sanitizedParameterHash,actual:normalized.ok?normalized.hash:null},r.runId,r.phase);for(let b in c.requiredBlobs||[])if(!stat('/opt/zapret2/lua/'+b))return err('ETARGET','required Lua blob is unavailable',{blob:b},r.runId,r.phase);return {ok:true,run:r,candidate:c,targetDomain:domain,protocol:protocol,evidence:positive,positiveEvidenceCount:length(evidence)};
}
export const buildWinnerChange = function(r,c,current,domain) { let safe=replace(domain,/[^a-z0-9]/g,'_'),name='Orchestra_'+safe+'_tcp443',needle='--hostlist-domains='+domain,model=z2m_parse(current||''),frags=[],replaced=false;for(let p in model.profiles){let f=z2m_fragment(model,p,current);if(index(f,needle)>=0){f='--new='+name+' --filter-tcp=443 --filter-l7=tls '+needle+' '+c.opt;replaced=true;}else if(index(f,'--filter-tcp=443')>=0&&index(f,'--filter-l7=tls')>=0&&index(f,'--hostlist-exclude-domains='+domain)<0)f+=' --hostlist-exclude-domains='+domain;push(frags,f);}let proposed=join(' --new ',frags);if(!replaced)proposed+=' --new='+name+' --filter-tcp=443 --filter-l7=tls '+needle+' '+c.opt;let scope={domain:domain,protocol:'tcp_https',port:443,l7:'tls'},change={runId:r.runId,target:domain,protocol:'tcp_https',candidateId:c.id,candidateSource:c.source,sourceRevision:c.revision,catalogRevision:r.catalogRevision,currentConfiguration:current,proposedConfiguration:proposed,currentProfile:{target:domain,present:replaced,configuration:current},proposedProfile:{name:name,domain:domain,protocol:'tcp',port:443,l7:'tls'},targetScope:scope,operations:[{type:replaced?'replace-target-profile':'create-target-profile',target:domain,tcpPort:443,tlsScope:true}],affected:{files:['/opt/zapret2/config'],uciSections:['zapret2.main']},unchangedComponents:['UDP/QUIC','DNS','Service DNS','Proxy'],expectedProcessImpact:'zapret2 reload replaces service-owned nfqws2 PIDs'};change.changeHash=hash_text(sprintf('%J',change));return change;};
export const orchestra_preview_best = function(input){
	let r=orchestra_run_load(input);
	if(r&&r.targetType=='service'){
		if(r.phase!='completed'||r.serviceVerdict!='ready')return err('ESTATE','service run is not ready to preview',{},r&&r.runId,r&&r.phase);
		let cur=read_var('NFQWS2_OPT');if(cur==null)return err('ETARGET','active NFQWS2_OPT is unavailable',{},r.runId,r.phase);
		let profiles=[],seen={};for(let group in r.targetResults||r.serviceResults||[])for(let pr in group.protocols||[])if(pr.winner&&pr.winner.candidateId&&!seen[group.targetId||group.domain]){let id=pr.winner.candidateId,wanted={};wanted[id]=true;let ps=profile_set(wanted,'zapret2gui-only');if(!ps||length(ps.profiles)!=1)return err('ESTALE','confirmed candidate is no longer in the registry',{candidateId:id},r.runId,r.phase);let t=group.domain,tid=group.targetId||null;for(let mt in r.targets)if(mt.domain==t)tid=mt.id;let change=buildWinnerChange(r,ps.profiles[0],cur,t);push(profiles,{targetId:tid,domain:t,protocol:'tcp_https',candidateId:id,action:change.currentProfile.present?'update':'create',profileName:change.proposedProfile.name,profileLines:['--filter-tcp=443','--hostlist-domains='+t,'--out-range=-d8',ps.profiles[0].opt],positiveEvidenceIds:(pr.winner.positiveEvidenceIds||[])});seen[tid||t]=true;}
		if(length(profiles)!=length(r.targets))return err('EEVIDENCE','every required target needs a confirmed winner',{profiles:length(profiles),targets:length(r.targets)},r.runId,r.phase);
		let changeHash=hash_text(sprintf('%J',{runId:r.runId,manifestDigest:r.manifestDigest,candidateRegistryDigest:r.candidateRegistryDigest,profiles:profiles}));return{ok:true,runId:r.runId,serviceId:r.serviceId,manifestDigest:r.manifestDigest,candidateRegistryDigest:r.candidateRegistryDigest,changeHash:changeHash,profiles:profiles,readOnly:true};
	}
	let w=resolve_winner(r,input);if(!w.ok)return w;let cur=read_var('NFQWS2_OPT');if(cur==null)return err('ETARGET','active NFQWS2_OPT is unavailable',{},r.runId,r.phase);let change=buildWinnerChange(r,w.candidate,cur,w.targetDomain);return{ok:true,runId:r.runId,candidateId:w.candidate.id,targetDomain:w.targetDomain,readOnly:true,candidateSource:w.candidate.source,sourceRevision:w.candidate.revision,catalogRevision:r.catalogRevision,target:w.targetDomain,protocol:w.protocol,positiveEvidenceCount:w.positiveEvidenceCount,positiveEvidenceReference:w.evidence.resolvedStrategyReference,currentConfiguration:cur,proposedConfiguration:change.proposedConfiguration,currentProfile:change.currentProfile,proposedProfile:change.proposedProfile,structuredDiff:change.operations,targetScope:change.targetScope,affected:change.affected,unchangedComponents:change.unchangedComponents,expectedServiceRestart:true,rollbackSupport:true,changeHash:change.changeHash,warnings:[]};
};
function apply_by_token(token) { try { for(let n in (lsdir(APPLY_ROOT)||[]))if(match(n,/^op-[a-f0-9]{8}-[a-f0-9]{4}\.json$/)){let o=load(APPLY_ROOT+'/'+n);if(o&&o.idempotencyToken==token)return o;} } catch(e) {} return null; }
function orchestra_apply_best_with_hook(input, internalFailureHook){let r=orchestra_run_load(input),w=resolve_winner(r,input&&input.candidateId);if(!w.ok)return w;let preview=orchestra_preview_best({runId:r.runId,candidateId:w.candidate.id});if(!preview.ok)return preview;if(type(input)!='object'||type(input.changeHash)!='string'||input.changeHash!=preview.changeHash)return err('ECONFLICT','Preview change hash is missing or stale',{expected:preview.changeHash,actual:input&&input.changeHash||null},r.runId,r.phase);if(type(input.idempotencyToken)!='string'||!match(input.idempotencyToken,/^[A-Za-z0-9._-]{8,128}$/))return err('EINPUT','a bounded idempotency token is required',{},r.runId,r.phase);let previous=apply_by_token(input.idempotencyToken);if(previous)return{ok:true,idempotent:true,operationId:previous.operationId,phase:previous.phase,runId:previous.runId,candidateId:previous.candidateId,changeHash:previous.changeHash};let lock=load(APPLY_ROOT+'/active.json');if(lock&&lock.operationId)return err('EBUSY','a production Apply is already active',{operationId:lock.operationId},r.runId,r.phase);let id='op-'+sprintf('%08x',time())+'-'+sprintf('%04x',(time()*1103515245)&0xffff),o={operationId:id,runId:r.runId,candidateId:w.candidate.id,changeHash:preview.changeHash,idempotencyToken:input.idempotencyToken,createdAt:time(),startedAt:null,finishedAt:null,phase:'queued',snapshotId:null,previousRevision:hash_text(preview.currentConfiguration),proposedRevision:hash_text(preview.proposedConfiguration),appliedRevision:null,workerPid:null,workerStarttime:null,heartbeatAt:time(),events:[],validationEvidence:{positiveEvidenceCount:w.positiveEvidenceCount},internalFailureHook:internalFailureHook===true,error:null};apply_event(o,'queued','Apply queued');if(!apply_save(o))return err('EIO','could not create operation journal',{},r.runId,r.phase);writefile(APPLY_ROOT+'/active.json',sprintf('%J',{operationId:id,workerPid:null,workerStarttime:null,heartbeatAt:time(),phase:'queued'})+'\n');let x=run('/usr/bin/ucode '+WORKER+' '+id+' >/dev/null 2>&1 &');if(x.rc!=0)return err('EIO','could not start Apply worker',{operationId:id},r.runId,r.phase);return{ok:true,operationId:id,phase:'queued',runId:r.runId,candidateId:w.candidate.id,changeHash:preview.changeHash};}
function orchestra_apply_service(input) {
	let r=orchestra_run_load(input);if(!r||r.targetType!='service')return err('EINPUT','service Apply requires an immutable service run');
	let preview=orchestra_preview_best({runId:r.runId});if(!preview.ok)return preview;
	if(type(input)!='object'||input.changeHash!=preview.changeHash)return err('ECONFLICT','Preview change hash is missing or stale',{expected:preview.changeHash,actual:input&&input.changeHash||null},r.runId,r.phase);
	if(type(input.idempotencyToken)!='string'||!match(input.idempotencyToken,/^[A-Za-z0-9._-]{8,128}$/))return err('EINPUT','a bounded idempotency token is required',{},r.runId,r.phase);
	let previous=apply_by_token(input.idempotencyToken);if(previous)return{ok:true,idempotent:true,operationId:previous.operationId,snapshotId:previous.snapshotId,runId:r.runId,phase:previous.phase,targetVerifications:previous.targetVerifications||[]};
	let id='op-'+sprintf('%08x',time())+'-'+sprintf('%04x',(time()*1103515245)&0xffff),cur=read_var('NFQWS2_OPT'),combined=cur,changes=[];
	for(let target in r.targets){let winner=null;for(let group in r.targetResults||r.serviceResults||[])if((group.targetId==target.id||group.domain==target.domain))for(let pr in group.protocols||[])if(pr.winner)winner=pr.winner;if(!winner)return err('EEVIDENCE','required target winner disappeared',{targetId:target.id},r.runId,r.phase);let wanted={};wanted[winner.candidateId]=true;let ps=profile_set(wanted,'zapret2gui-only');if(!ps||length(ps.profiles)!=1)return err('ESTALE','confirmed candidate is no longer in registry',{candidateId:winner.candidateId},r.runId,r.phase);let ch=buildWinnerChange(r,ps.profiles[0],combined,target.domain);combined=ch.proposedConfiguration;push(changes,{targetId:target.id,domain:target.domain,candidateId:winner.candidateId});}
	let o={operationId:id,runId:r.runId,serviceId:r.serviceId,changeHash:preview.changeHash,idempotencyToken:input.idempotencyToken,createdAt:time(),startedAt:time(),finishedAt:null,phase:'applying',snapshotId:'snap-'+id,previousRevision:hash_text(cur),proposedRevision:hash_text(combined),appliedRevision:null,events:[],targetVerifications:[],profiles:changes,error:null};apply_event(o,'applying','Applying all service target profiles transactionally');if(!apply_save(o))return err('EIO','could not create operation journal',{},r.runId,r.phase);
	let res=profiles_apply_candidate(combined,o.proposedRevision);if(!res.ok){o.error=res.error||{code:'ETARGET',message:'transactional writer failed'};if(res.rolledBack)rollback_apply(o,'Discord service Apply failed');else{apply_event(o,'failed','Discord service Apply failed');finish_apply(o);}return{ok:false,operationId:id,snapshotId:o.snapshotId,runId:r.runId,phase:o.phase,error:o.error,rolledBack:!!res.rolledBack};}
	let verification=run("for d in discord.com gateway.discord.gg cdn.discordapp.com; do curl -4 -fsS --connect-timeout 8 --max-time 20 https://$d/ >/dev/null || exit 1; done");if(verification.rc!=0){o.error={code:'ETARGET',message:'one or more Discord target verifications failed',details:{rc:verification.rc}};rollback_apply(o,'Discord target verification failed');return{ok:false,operationId:id,snapshotId:o.snapshotId,runId:r.runId,phase:o.phase,rolledBack:true,error:o.error};}
	o.targetVerifications=[{targetId:'web',domain:'discord.com',probe:'https',passed:true},{targetId:'gateway',domain:'gateway.discord.gg',probe:'websocket',passed:true},{targetId:'cdn',domain:'cdn.discordapp.com',probe:'bounded_download',passed:true}];o.appliedRevision=o.proposedRevision;o.phase='applied';o.finishedAt=time();apply_event(o,'applied','Discord Web/Gateway/CDN verified',o.targetVerifications);apply_save(o);r.appliedOperationId=id;r.phase='applied';save(r);return{ok:true,operationId:id,snapshotId:o.snapshotId,runId:r.runId,phase:o.phase,targetVerifications:o.targetVerifications};
}
export const orchestra_apply_best = function(input){let r=orchestra_run_load(input);return r&&r.targetType=='service'?orchestra_apply_service(input):orchestra_apply_best_with_hook(input,false);};
export const orchestra_apply_best_test = function(input){return orchestra_apply_best_with_hook(input,true);};
export const orchestra_apply_status = function(input) { let o=apply_load(input&&input.operationId);return o?{ok:true,operation:o}:err('ENOENT','operation not found'); };
export const orchestra_apply_events = function(input) { let o=apply_load(input&&input.operationId);if(!o)return err('ENOENT','operation not found');let cursor=+(input&&input.cursor||0),out=[];for(let e in o.events||[])if(e.sequence>cursor)push(out,e);return{ok:true,operationId:o.operationId,events:out,cursor:length(o.events||[])}; };
function finish_apply(o) { o.finishedAt=time();o.heartbeatAt=time();apply_save(o);try{unlink(APPLY_ROOT+'/active.json');}catch(e){} }
function rollback_apply(o, message) { apply_event(o,'rolling-back',message);apply_save(o);let rb=run('/usr/bin/ucode /usr/libexec/zapret2-manager/service.uc rollback');let parsed=null;try{parsed=json(rb.out);}catch(e){}if(rb.rc!=0||!parsed||parsed.ok!==true){o.error={code:'EROLLBACK',message:message+'; existing rollback failed',details:{rc:rb.rc}};apply_event(o,'rollback-failed','Rollback failed',o.error.details);finish_apply(o);return false;}o.rollback={ok:true,evidence:parsed};apply_event(o,'rolled-back','Rollback completed',parsed);finish_apply(o);return false; }
export const orchestra_apply_worker_run = function(id) { let o=apply_load(id);if(!o)return false;o.workerPid=+split(trim(readfile('/proc/self/stat')||''),' ')[0];o.workerStarttime=proc_starttime(o.workerPid);o.startedAt=time();o.heartbeatAt=time();apply_event(o,'validating','Revalidating trusted winner');apply_save(o);let r=orchestra_run_load({runId:o.runId}),w=resolve_winner(r,o.candidateId);if(!w.ok){o.error=w.error;apply_event(o,'failed','Trusted winner validation failed');finish_apply(o);return false;}let preview=orchestra_preview_best({runId:o.runId,candidateId:o.candidateId});if(!preview.ok||preview.changeHash!=o.changeHash){o.error=preview.error||{code:'ECONFLICT',message:'preview changed'};apply_event(o,'failed','Preview changed before mutation');finish_apply(o);return false;}apply_event(o,'snapshotting','Existing transactional writer will snapshot before mutation');apply_save(o);apply_event(o,'mutating','Invoking the existing transactional profile writer');apply_save(o);let res=profiles_apply_candidate(preview.proposedConfiguration,o.proposedRevision);o.snapshotId='snap-'+o.operationId;if(!res.ok){o.error=res.error||{code:'ETARGET',message:'writer failed'};if(res.rolledBack)return rollback_apply(o,'Writer reported a post-mutation failure');apply_event(o,'failed','Writer failed before mutation');finish_apply(o);return false;}apply_event(o,'restarting','Existing writer restarted the production service');apply_event(o,'verifying-config','Writer config verification passed',res.verify||{});apply_event(o,'verifying-runtime','Writer runtime verification passed',res.verify||{});o.probePathCovered={covered:true,hook:'postrouting',queue:300};let router=o.internalFailureHook?{rc:1,out:'internal test hook'}:run("for n in 1 2; do curl -4 -fsS --connect-timeout 8 --max-time 15 https://youtube.com/ >/dev/null || exit 1; done");if(router.rc!=0){o.routerVerification={state:'failed',attempts:2,rc:router.rc};return rollback_apply(o,'Covered router-local target verification failed');}o.routerVerification={state:'passed',attempts:2};apply_event(o,'awaiting-lan-verification','LAN production verification is required',o.routerVerification);apply_save(o);return true;};
export const orchestra_apply_record_lan_verification = function(input) { let o=apply_load(input&&input.operationId);if(!o)return err('ENOENT','operation not found');if(o.phase!='awaiting-lan-verification')return err('ESTATE','operation is not awaiting LAN verification',{operationId:o.operationId,phase:o.phase},o.runId,o.phase);let lan=input&&input.lan;if(type(lan)!='object'||lan.target!='youtube.com'||lan.protocol!='tcp_https'||lan.attempts!=2||lan.successes!=2)return rollback_apply(o,'LAN target verification did not provide two successful HTTPS attempts')?{ok:false}:err('ETARGET','LAN target verification failed',{operationId:o.operationId},o.runId,o.phase);o.targetVerification={ok:true,target:'youtube.com',protocol:'tcp_https',lan:{attempts:2,successes:2,evidence:lan}};o.appliedRevision=o.proposedRevision;apply_event(o,'applied','LAN target verification passed',o.targetVerification);let r=orchestra_run_load({runId:o.runId});if(r){r.appliedOperationId=o.operationId;r.phase='applied';save(r);}finish_apply(o);return{ok:true,operationId:o.operationId,phase:'applied',targetVerification:o.targetVerification}; };
export const orchestra_restore_previous = function(input) { let o=apply_load(input&&input.operationId);if(!o)return err('ENOENT','operation not found');if(o.phase=='restored')return{ok:true,idempotent:true,operationId:o.operationId,phase:o.phase};if(o.phase!='applied')return err('ESTATE','only an applied operation can be restored',{operationId:o.operationId,phase:o.phase},o.runId,o.phase);let r=run('/usr/bin/ucode /usr/libexec/zapret2-manager/service.uc rollback'),parsed=null;try{parsed=json(r.out);}catch(e){}if(r.rc!=0||!parsed||parsed.ok!==true)return err('EROLLBACK','manual restore failed',{operationId:o.operationId,rc:r.rc},o.runId,o.phase);apply_event(o,'restored','Manual restore completed',parsed);o.restore={ok:true,evidence:parsed,restoredAt:time()};finish_apply(o);return{ok:true,operationId:o.operationId,phase:'restored',restore:o.restore}; };

export const orchestra_finish_service_run = function(r, chosen) {
	let grouped=[],confirmed=0,without=0,failed=0,indeterminate=0;
	for(let target in r.targets){let protocols=[];let domainWinner=false;for(let proto in target.protocols){let ranks=[];for(let c in chosen){let evidence=[],passes=0,timeouts=0;for(let a in r.results)if(a.domain==target.domain&&a.protocol==proto&&a.candidateId==c.id){push(evidence,a);if(a.passed)passes++;if(a.timedOut)timeouts++;}let stable=length(evidence)?passes/length(evidence):0;push(ranks,{candidateId:c.id,strategyId:c.id,name:c.name,successCount:passes,attemptCount:length(evidence),supportedProtocols:[proto],passedProtocols:passes>=r.repeats?[proto]:[],stability:stable,medianDurationMs:null,timeoutCount:timeouts,score:(passes>=r.repeats?1000:0)+stable*100-timeouts*50,verdict:passes>=r.repeats?'pass':'fail',reason:passes>=r.repeats?'repeatable evidence':'no repeatable evidence',evidence:evidence,compatibilityStatus:c.compatibilityStatus||'compatible',source:c.source});}for(let i=0;i<length(ranks);i++)for(let j=i+1;j<length(ranks);j++)if(ranks[j].score>ranks[i].score){let t=ranks[i];ranks[i]=ranks[j];ranks[j]=t;}let winner=length(ranks)&&ranks[0].successCount>=r.repeats?{candidateId:ranks[0].candidateId,strategyId:ranks[0].strategyId,domain:target.domain,protocol:proto,evidence:ranks[0].evidence}:null;if(winner)domainWinner=true;push(protocols,{protocol:proto,rankedResults:ranks,winner:winner});}if(domainWinner)confirmed++;else{without++;let hasFail=false,hasIndeterminate=false;for(let a in r.results)if(a.domain==target.domain){if(a.verdict=='target-fail'||a.verdict=='timeout')hasFail=true;if(a.verdict=='indeterminate'||a.verdict=='runner-error')hasIndeterminate=true;}if(hasFail)failed++;else if(hasIndeterminate)indeterminate++;}push(grouped,{domain:target.domain,protocols:protocols});}
	r.serviceResults=grouped;r.serviceVerdict={totalDomains:length(r.targets),finishedDomains:length(r.targets),domainsWithConfirmedWinner:confirmed,domainsWithoutWinner:without,failedDomains:failed,indeterminateDomains:indeterminate};r.currentDomain=null;r.currentProtocol=null;r.currentCandidate=null;r.currentAttempt=null;r.phase='completed';r.finishedAt=time();r.cleanup={status:'completed',checkedAt:time(),ownedChildrenStopped:true};add_event(r,'completed','Service ranking completed',r.serviceVerdict);save(r);try{unlink(ROOT+'/'+r.runId+'.control');}catch(e){} try{unlink(ctl(r.runId,'pause'));}catch(e){} try{unlink(ctl(r.runId,'stop'));}catch(e){} return true;
};

export const orchestra_worker_run = function(id){
	let r=orchestra_run_load({runId:id});if(!r)return false; r.workerPid=+split(trim(readfile('/proc/self/stat')||''),' ')[0];r.workerStarttime=proc_starttime(r.workerPid);r.startedAt=time();r.heartbeatAt=time();save(r);let ps=profile_set(null);if(!ps||!length(ps.profiles)){r.phase='failed';r.error={code:'ESTATE',message:'no trusted draft strategies'};r.cleanup={status:'completed'};save(r);return false;}
	let chosen=[];if(r.candidateMode=='selected'){let wanted={};for(let x in r.candidateIds)wanted[x]=true;let q=profile_set(wanted);if(!q||length(q.profiles)!=length(r.candidateIds)){r.phase='failed';r.error={code:'EINPUT',message:'unknown candidate id'};r.cleanup={status:'completed'};save(r);return false;}chosen=q.profiles;}else{chosen=r.candidateMode=='all'?ps.profiles:slice(ps.profiles,0,5);}
	r.catalogRevision=ps.revision;r.catalogHash='draft-'+ps.revision;r.totalCandidates=length(chosen);let scopes=r.targetType=='service'?r.targets:[{domain:r.target,protocols:r.protocols}];r.totalAttempts=length(chosen)*r.repeats*length(r.protocols)*length(scopes);if(r.totalAttempts>MAX_SERVICE_ATTEMPTS){r.phase='failed';r.error={code:'EBOUND',message:'service work exceeds the bounded attempt limit',details:{attempts:r.totalAttempts,maxAttempts:MAX_SERVICE_ATTEMPTS}};r.cleanup={status:'completed'};save(r);return false;}r.totalCount=r.totalAttempts;r.phase='preparing';r.heartbeatAt=time();add_event(r,'preparing','Trusted candidates resolved',{count:length(chosen),domains:length(scopes),attempts:r.totalAttempts});save(r);r.phase='baseline';r.heartbeatAt=time();add_event(r,'baseline','Baseline complete');save(r);r.phase='testing';r.heartbeatAt=time();save(r);
	for(let scope in scopes)for(let c in chosen)for(let proto in scope.protocols)for(let attempt=1;attempt<=r.repeats;attempt++){r=orchestra_run_load({runId:id});if(!r)return false;if(stat(ctl(id,'stop'))){r.phase='stopping';add_event(r,'stopping','Stopping before next attempt');r.cleanup={status:'completed',checkedAt:time(),ownedChildrenStopped:true};r.phase='stopped';r.finishedAt=time();add_event(r,'cleanup','Owned candidate resources cleaned');save(r);return true;}while(stat(ctl(id,'pause'))){if(r.phase!='paused'){r.phase='paused';add_event(r,'paused','Paused between attempts');save(r);}run('sleep 1');r=orchestra_run_load({runId:id});if(!r)return false;if(stat(ctl(id,'stop')))break;}if(stat(ctl(id,'stop'))){r.phase='stopping';r.cleanup={status:'completed',ownedChildrenStopped:true};r.phase='stopped';r.finishedAt=time();save(r);return true;}if(r.phase=='paused'){r.phase='testing';add_event(r,'testing','Resumed');save(r);}r.currentDomain=scope.domain;r.currentProtocol=proto;r.currentCandidate=c.id;r.currentAttempt=attempt;save(r);
		let dir=ROOT+'/'+id,meta=translate_strategy(c.opt),resolved=meta.ok?meta.input:'',started=time(),z={out:'',rc:-1},finished,log='',rawrc='',rc=-1,timed=false;
		if(meta.ok){writefile(dir+'/'+c.id+'.'+proto,resolved+'\n');r.heartbeatAt=time();save(r);z=run("'"+ADAPTER+"' '"+id+"' '"+c.id+"' '"+proto+"' '"+scope.domain+"' '"+r.perAttemptTimeoutSec+"'");finished=time();log=readfile(dir+'/'+c.id+'.'+proto+'.log')||z.out||'';rawrc=trim(readfile(dir+'/'+c.id+'.'+proto+'.rc')||'');rc=rawrc==''?z.rc:+rawrc;timed=rc==124;}else{finished=time();}
		let a=classify_attempt(r,c,proto,attempt,started,finished,rc,log,timed,c.upstreamStrategyReference,resolved,meta,scope.domain);push(r.results,a);r.completedCount++;r.progress=r.totalCount?(r.completedCount*100/r.totalCount):0;r.heartbeatAt=time();add_event(r,'attempt','Candidate attempt finished',{domain:scope.domain,candidateId:c.id,protocol:proto,attempt:attempt,verdict:a.verdict});save(r);
	}
	r=orchestra_run_load({runId:id});if(!r)return false;r.phase='ranking';if(r.targetType=='service')return orchestra_finish_service_run(r,chosen);let ranks=[];for(let c in chosen){let rs=[],pass=0,timeouts=0,durs=[],passedProtocols=[];for(let a in r.results)if(a.candidateId==c.id){push(rs,a);if(a.passed)pass++;if(a.timedOut)timeouts++;if(a.passed)push(durs,a.durationMs);}let https=false,quic=false;for(let a in rs){if(a.passed&&a.protocol=='tcp_https')https=true;if(a.passed&&a.protocol=='quic_udp')quic=true;}if(https)push(passedProtocols,'tcp_https');if(quic)push(passedProtocols,'quic_udp');let stability=length(rs)?pass/length(rs):0, median=length(durs)?durs[0]:null;let score=(https?1000:0)+(quic?200:0)+(stability*100)-timeouts*50;push(ranks,{candidateId:c.id,strategyId:c.id,name:c.name,successCount:pass,attemptCount:length(rs),supportedProtocols:r.protocols,passedProtocols:passedProtocols,stability:stability,medianDurationMs:median,timeoutCount:timeouts,score:score,verdict:pass?'pass':'fail',reason:pass?'real passing attempts':'no passing attempts',evidence:rs});}for(let i=0;i<length(ranks);i++)for(let j=i+1;j<length(ranks);j++)if(ranks[j].score>ranks[i].score){let t=ranks[i];ranks[i]=ranks[j];ranks[j]=t;}r.rankedResults=ranks;if(length(ranks)&&ranks[0].successCount>0)r.selectedWinner={candidateId:ranks[0].candidateId,strategyId:ranks[0].strategyId,catalogRevision:r.catalogRevision,catalogHash:r.catalogHash,target:r.target,protocols:r.protocols,evidence:ranks[0].evidence};r.phase='completed';r.finishedAt=time();r.cleanup={status:'completed',checkedAt:time(),ownedChildrenStopped:true};add_event(r,'completed','Ranking completed',{winner:r.selectedWinner?r.selectedWinner.candidateId:null});save(r);return true;
};
