#!/usr/bin/ucode
'use strict';
import { writefile,unlink,popen } from 'fs';
const CLI='/usr/libexec/zapret2-manager/engine-cli.uc',MAX_EDIT=16384,MAX_OUTPUT=262144,TMP_PREFIX='/tmp/z2m-engine-edit.';
function request(req){let edit=null;try{if(req&&req.args&&req.args.edit!=null)edit=req.args.edit;}catch(e){}if(edit==null)try{if(req&&req.edit!=null)edit=req.edit;}catch(e){}return edit;}
function parse(value){try{let r=json(value||'');return r!=null?r:{ok:false,error:{code:'EINTERNAL',message:'Engine backend returned no response.'}};}catch(e){return{ok:false,error:{code:'EINTERNAL',message:'Engine backend response is invalid.'}};}}
function tempfile(){let p=popen('umask 077; mktemp /tmp/z2m-engine-edit.XXXXXX 2>/dev/null','r');if(!p)return null;let file=trim(p.read('all')||'');p.close();if(!length(file)||index(file,TMP_PREFIX)!=0||length(file)>64){if(length(file)&&index(file,TMP_PREFIX)==0)try{unlink(file);}catch(e){}return null;}return file;}
function cleanup(file){if(file)try{unlink(file);}catch(e){}}
function action(mode,edit){let file=null,cmd='/usr/bin/ucode '+CLI+' '+mode;if(edit!=null){if(type(edit)!='string'||length(edit)>MAX_EDIT)return{ok:false,error:{code:'EINPUT',message:'edit must be a bounded JSON string.'}};file=tempfile();if(!file)return{ok:false,error:{code:'EINTERNAL',message:'Failed to create a private engine request file.'}};if(!writefile(file,edit)){cleanup(file);return{ok:false,error:{code:'EINTERNAL',message:'Failed to stage engine request.'}};}cmd+=' '+file;}let p=popen(cmd+' 2>/dev/null | head -c '+MAX_OUTPUT,'r');if(!p){cleanup(file);return{ok:false,error:{code:'ETARGET',message:'Engine backend is unavailable.'}};}let out=p.read('all')||'';p.close();cleanup(file);return parse(out);}
function edited(mode,req){let e=request(req);return e==null?{ok:false,error:{code:'EINPUT',message:'Missing edit param.'}}:action(mode,e);}
return{'zapret2-manager-engine':{engine_providers:{call:function(req){return action('providers',null);}},engine_status:{call:function(req){return action('status',null);}},engine_check_updates:{args:{edit:'string'},call:function(req){return edited('check',req);}},engine_install:{args:{edit:'string'},call:function(req){return edited('install',req);}},engine_remove:{args:{edit:'string'},call:function(req){return edited('remove',req);}},engine_operation_status:{args:{edit:'string'},call:function(req){return edited('operation',req);}},engine_operation_cancel:{args:{edit:'string'},call:function(req){return edited('cancel',req);}}}};
